// Code generated by ent, DO NOT EDIT.

package insurancepolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldUpdateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldName, v))
}

// PolicyNumber applies equality check predicate on the "policy_number" field. It's identical to PolicyNumberEQ.
func PolicyNumber(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldPolicyNumber, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldProvider, v))
}

// CoverageType applies equality check predicate on the "coverage_type" field. It's identical to CoverageTypeEQ.
func CoverageType(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCoverageType, v))
}

// PremiumAmount applies equality check predicate on the "premium_amount" field. It's identical to PremiumAmountEQ.
func PremiumAmount(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldPremiumAmount, v))
}

// Deductible applies equality check predicate on the "deductible" field. It's identical to DeductibleEQ.
func Deductible(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldDeductible, v))
}

// CoverageLimit applies equality check predicate on the "coverage_limit" field. It's identical to CoverageLimitEQ.
func CoverageLimit(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCoverageLimit, v))
}

// ValidFrom applies equality check predicate on the "valid_from" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldValidFrom, v))
}

// ValidTo applies equality check predicate on the "valid_to" field. It's identical to ValidToEQ.
func ValidTo(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldValidTo, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldNotes, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldCreateBy))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldUpdateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldTenantID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldName, v))
}

// PolicyNumberEQ applies the EQ predicate on the "policy_number" field.
func PolicyNumberEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldPolicyNumber, v))
}

// PolicyNumberNEQ applies the NEQ predicate on the "policy_number" field.
func PolicyNumberNEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldPolicyNumber, v))
}

// PolicyNumberIn applies the In predicate on the "policy_number" field.
func PolicyNumberIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldPolicyNumber, vs...))
}

// PolicyNumberNotIn applies the NotIn predicate on the "policy_number" field.
func PolicyNumberNotIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldPolicyNumber, vs...))
}

// PolicyNumberGT applies the GT predicate on the "policy_number" field.
func PolicyNumberGT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldPolicyNumber, v))
}

// PolicyNumberGTE applies the GTE predicate on the "policy_number" field.
func PolicyNumberGTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldPolicyNumber, v))
}

// PolicyNumberLT applies the LT predicate on the "policy_number" field.
func PolicyNumberLT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldPolicyNumber, v))
}

// PolicyNumberLTE applies the LTE predicate on the "policy_number" field.
func PolicyNumberLTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldPolicyNumber, v))
}

// PolicyNumberContains applies the Contains predicate on the "policy_number" field.
func PolicyNumberContains(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContains(FieldPolicyNumber, v))
}

// PolicyNumberHasPrefix applies the HasPrefix predicate on the "policy_number" field.
func PolicyNumberHasPrefix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasPrefix(FieldPolicyNumber, v))
}

// PolicyNumberHasSuffix applies the HasSuffix predicate on the "policy_number" field.
func PolicyNumberHasSuffix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasSuffix(FieldPolicyNumber, v))
}

// PolicyNumberIsNil applies the IsNil predicate on the "policy_number" field.
func PolicyNumberIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldPolicyNumber))
}

// PolicyNumberNotNil applies the NotNil predicate on the "policy_number" field.
func PolicyNumberNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldPolicyNumber))
}

// PolicyNumberEqualFold applies the EqualFold predicate on the "policy_number" field.
func PolicyNumberEqualFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldPolicyNumber, v))
}

// PolicyNumberContainsFold applies the ContainsFold predicate on the "policy_number" field.
func PolicyNumberContainsFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldPolicyNumber, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldProvider, v))
}

// CoverageTypeEQ applies the EQ predicate on the "coverage_type" field.
func CoverageTypeEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCoverageType, v))
}

// CoverageTypeNEQ applies the NEQ predicate on the "coverage_type" field.
func CoverageTypeNEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldCoverageType, v))
}

// CoverageTypeIn applies the In predicate on the "coverage_type" field.
func CoverageTypeIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldCoverageType, vs...))
}

// CoverageTypeNotIn applies the NotIn predicate on the "coverage_type" field.
func CoverageTypeNotIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldCoverageType, vs...))
}

// CoverageTypeGT applies the GT predicate on the "coverage_type" field.
func CoverageTypeGT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldCoverageType, v))
}

// CoverageTypeGTE applies the GTE predicate on the "coverage_type" field.
func CoverageTypeGTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldCoverageType, v))
}

// CoverageTypeLT applies the LT predicate on the "coverage_type" field.
func CoverageTypeLT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldCoverageType, v))
}

// CoverageTypeLTE applies the LTE predicate on the "coverage_type" field.
func CoverageTypeLTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldCoverageType, v))
}

// CoverageTypeContains applies the Contains predicate on the "coverage_type" field.
func CoverageTypeContains(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContains(FieldCoverageType, v))
}

// CoverageTypeHasPrefix applies the HasPrefix predicate on the "coverage_type" field.
func CoverageTypeHasPrefix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasPrefix(FieldCoverageType, v))
}

// CoverageTypeHasSuffix applies the HasSuffix predicate on the "coverage_type" field.
func CoverageTypeHasSuffix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasSuffix(FieldCoverageType, v))
}

// CoverageTypeIsNil applies the IsNil predicate on the "coverage_type" field.
func CoverageTypeIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldCoverageType))
}

// CoverageTypeNotNil applies the NotNil predicate on the "coverage_type" field.
func CoverageTypeNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldCoverageType))
}

// CoverageTypeEqualFold applies the EqualFold predicate on the "coverage_type" field.
func CoverageTypeEqualFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldCoverageType, v))
}

// CoverageTypeContainsFold applies the ContainsFold predicate on the "coverage_type" field.
func CoverageTypeContainsFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldCoverageType, v))
}

// PremiumAmountEQ applies the EQ predicate on the "premium_amount" field.
func PremiumAmountEQ(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldPremiumAmount, v))
}

// PremiumAmountNEQ applies the NEQ predicate on the "premium_amount" field.
func PremiumAmountNEQ(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldPremiumAmount, v))
}

// PremiumAmountIn applies the In predicate on the "premium_amount" field.
func PremiumAmountIn(vs ...float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldPremiumAmount, vs...))
}

// PremiumAmountNotIn applies the NotIn predicate on the "premium_amount" field.
func PremiumAmountNotIn(vs ...float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldPremiumAmount, vs...))
}

// PremiumAmountGT applies the GT predicate on the "premium_amount" field.
func PremiumAmountGT(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldPremiumAmount, v))
}

// PremiumAmountGTE applies the GTE predicate on the "premium_amount" field.
func PremiumAmountGTE(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldPremiumAmount, v))
}

// PremiumAmountLT applies the LT predicate on the "premium_amount" field.
func PremiumAmountLT(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldPremiumAmount, v))
}

// PremiumAmountLTE applies the LTE predicate on the "premium_amount" field.
func PremiumAmountLTE(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldPremiumAmount, v))
}

// PremiumAmountIsNil applies the IsNil predicate on the "premium_amount" field.
func PremiumAmountIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldPremiumAmount))
}

// PremiumAmountNotNil applies the NotNil predicate on the "premium_amount" field.
func PremiumAmountNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldPremiumAmount))
}

// DeductibleEQ applies the EQ predicate on the "deductible" field.
func DeductibleEQ(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldDeductible, v))
}

// DeductibleNEQ applies the NEQ predicate on the "deductible" field.
func DeductibleNEQ(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldDeductible, v))
}

// DeductibleIn applies the In predicate on the "deductible" field.
func DeductibleIn(vs ...float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldDeductible, vs...))
}

// DeductibleNotIn applies the NotIn predicate on the "deductible" field.
func DeductibleNotIn(vs ...float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldDeductible, vs...))
}

// DeductibleGT applies the GT predicate on the "deductible" field.
func DeductibleGT(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldDeductible, v))
}

// DeductibleGTE applies the GTE predicate on the "deductible" field.
func DeductibleGTE(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldDeductible, v))
}

// DeductibleLT applies the LT predicate on the "deductible" field.
func DeductibleLT(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldDeductible, v))
}

// DeductibleLTE applies the LTE predicate on the "deductible" field.
func DeductibleLTE(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldDeductible, v))
}

// DeductibleIsNil applies the IsNil predicate on the "deductible" field.
func DeductibleIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldDeductible))
}

// DeductibleNotNil applies the NotNil predicate on the "deductible" field.
func DeductibleNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldDeductible))
}

// CoverageLimitEQ applies the EQ predicate on the "coverage_limit" field.
func CoverageLimitEQ(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldCoverageLimit, v))
}

// CoverageLimitNEQ applies the NEQ predicate on the "coverage_limit" field.
func CoverageLimitNEQ(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldCoverageLimit, v))
}

// CoverageLimitIn applies the In predicate on the "coverage_limit" field.
func CoverageLimitIn(vs ...float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldCoverageLimit, vs...))
}

// CoverageLimitNotIn applies the NotIn predicate on the "coverage_limit" field.
func CoverageLimitNotIn(vs ...float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldCoverageLimit, vs...))
}

// CoverageLimitGT applies the GT predicate on the "coverage_limit" field.
func CoverageLimitGT(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldCoverageLimit, v))
}

// CoverageLimitGTE applies the GTE predicate on the "coverage_limit" field.
func CoverageLimitGTE(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldCoverageLimit, v))
}

// CoverageLimitLT applies the LT predicate on the "coverage_limit" field.
func CoverageLimitLT(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldCoverageLimit, v))
}

// CoverageLimitLTE applies the LTE predicate on the "coverage_limit" field.
func CoverageLimitLTE(v float64) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldCoverageLimit, v))
}

// CoverageLimitIsNil applies the IsNil predicate on the "coverage_limit" field.
func CoverageLimitIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldCoverageLimit))
}

// CoverageLimitNotNil applies the NotNil predicate on the "coverage_limit" field.
func CoverageLimitNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldCoverageLimit))
}

// ValidFromEQ applies the EQ predicate on the "valid_from" field.
func ValidFromEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "valid_from" field.
func ValidFromNEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "valid_from" field.
func ValidFromIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "valid_from" field.
func ValidFromNotIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "valid_from" field.
func ValidFromGT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "valid_from" field.
func ValidFromGTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "valid_from" field.
func ValidFromLT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "valid_from" field.
func ValidFromLTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldValidFrom, v))
}

// ValidFromIsNil applies the IsNil predicate on the "valid_from" field.
func ValidFromIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldValidFrom))
}

// ValidFromNotNil applies the NotNil predicate on the "valid_from" field.
func ValidFromNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldValidFrom))
}

// ValidToEQ applies the EQ predicate on the "valid_to" field.
func ValidToEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldValidTo, v))
}

// ValidToNEQ applies the NEQ predicate on the "valid_to" field.
func ValidToNEQ(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldValidTo, v))
}

// ValidToIn applies the In predicate on the "valid_to" field.
func ValidToIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldValidTo, vs...))
}

// ValidToNotIn applies the NotIn predicate on the "valid_to" field.
func ValidToNotIn(vs ...time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldValidTo, vs...))
}

// ValidToGT applies the GT predicate on the "valid_to" field.
func ValidToGT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldValidTo, v))
}

// ValidToGTE applies the GTE predicate on the "valid_to" field.
func ValidToGTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldValidTo, v))
}

// ValidToLT applies the LT predicate on the "valid_to" field.
func ValidToLT(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldValidTo, v))
}

// ValidToLTE applies the LTE predicate on the "valid_to" field.
func ValidToLTE(v time.Time) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldValidTo, v))
}

// ValidToIsNil applies the IsNil predicate on the "valid_to" field.
func ValidToIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldValidTo))
}

// ValidToNotNil applies the NotNil predicate on the "valid_to" field.
func ValidToNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldValidTo))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldContainsFold(FieldNotes, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InsurancePolicy) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InsurancePolicy) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InsurancePolicy) predicate.InsurancePolicy {
	return predicate.InsurancePolicy(sql.NotPredicates(p))
}
