// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/asset"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/assetassignment"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/category"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/employee"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/location"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/supplier"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks     []Hook
	mutation  *AssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *AssetUpdate) SetCreateBy(v uint32) *AssetUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableCreateBy(v *uint32) *AssetUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *AssetUpdate) AddCreateBy(v int32) *AssetUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *AssetUpdate) ClearCreateBy() *AssetUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *AssetUpdate) SetUpdateBy(v uint32) *AssetUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableUpdateBy(v *uint32) *AssetUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *AssetUpdate) AddUpdateBy(v int32) *AssetUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *AssetUpdate) ClearUpdateBy() *AssetUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AssetUpdate) SetUpdateTime(v time.Time) *AssetUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableUpdateTime(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *AssetUpdate) ClearUpdateTime() *AssetUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *AssetUpdate) SetDeleteTime(v time.Time) *AssetUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableDeleteTime(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *AssetUpdate) ClearDeleteTime() *AssetUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetAssetTag sets the "asset_tag" field.
func (_u *AssetUpdate) SetAssetTag(v string) *AssetUpdate {
	_u.mutation.SetAssetTag(v)
	return _u
}

// SetNillableAssetTag sets the "asset_tag" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableAssetTag(v *string) *AssetUpdate {
	if v != nil {
		_u.SetAssetTag(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AssetUpdate) SetName(v string) *AssetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableName(v *string) *AssetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *AssetUpdate) ClearName() *AssetUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetSerial sets the "serial" field.
func (_u *AssetUpdate) SetSerial(v string) *AssetUpdate {
	_u.mutation.SetSerial(v)
	return _u
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableSerial(v *string) *AssetUpdate {
	if v != nil {
		_u.SetSerial(*v)
	}
	return _u
}

// ClearSerial clears the value of the "serial" field.
func (_u *AssetUpdate) ClearSerial() *AssetUpdate {
	_u.mutation.ClearSerial()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AssetUpdate) SetModelName(v string) *AssetUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableModelName(v *string) *AssetUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *AssetUpdate) ClearModelName() *AssetUpdate {
	_u.mutation.ClearModelName()
	return _u
}

// SetModelNumber sets the "model_number" field.
func (_u *AssetUpdate) SetModelNumber(v string) *AssetUpdate {
	_u.mutation.SetModelNumber(v)
	return _u
}

// SetNillableModelNumber sets the "model_number" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableModelNumber(v *string) *AssetUpdate {
	if v != nil {
		_u.SetModelNumber(*v)
	}
	return _u
}

// ClearModelNumber clears the value of the "model_number" field.
func (_u *AssetUpdate) ClearModelNumber() *AssetUpdate {
	_u.mutation.ClearModelNumber()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *AssetUpdate) SetCategoryID(v string) *AssetUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableCategoryID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *AssetUpdate) ClearCategoryID() *AssetUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetSupplierID sets the "supplier_id" field.
func (_u *AssetUpdate) SetSupplierID(v string) *AssetUpdate {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableSupplierID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// ClearSupplierID clears the value of the "supplier_id" field.
func (_u *AssetUpdate) ClearSupplierID() *AssetUpdate {
	_u.mutation.ClearSupplierID()
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *AssetUpdate) SetLocationID(v string) *AssetUpdate {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableLocationID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// ClearLocationID clears the value of the "location_id" field.
func (_u *AssetUpdate) ClearLocationID() *AssetUpdate {
	_u.mutation.ClearLocationID()
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *AssetUpdate) SetEmployeeID(v string) *AssetUpdate {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableEmployeeID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// ClearEmployeeID clears the value of the "employee_id" field.
func (_u *AssetUpdate) ClearEmployeeID() *AssetUpdate {
	_u.mutation.ClearEmployeeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AssetUpdate) SetStatus(v int32) *AssetUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableStatus(v *int32) *AssetUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AssetUpdate) AddStatus(v int32) *AssetUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPhotoKey sets the "photo_key" field.
func (_u *AssetUpdate) SetPhotoKey(v string) *AssetUpdate {
	_u.mutation.SetPhotoKey(v)
	return _u
}

// SetNillablePhotoKey sets the "photo_key" field if the given value is not nil.
func (_u *AssetUpdate) SetNillablePhotoKey(v *string) *AssetUpdate {
	if v != nil {
		_u.SetPhotoKey(*v)
	}
	return _u
}

// ClearPhotoKey clears the value of the "photo_key" field.
func (_u *AssetUpdate) ClearPhotoKey() *AssetUpdate {
	_u.mutation.ClearPhotoKey()
	return _u
}

// SetWarrantyMonths sets the "warranty_months" field.
func (_u *AssetUpdate) SetWarrantyMonths(v int32) *AssetUpdate {
	_u.mutation.ResetWarrantyMonths()
	_u.mutation.SetWarrantyMonths(v)
	return _u
}

// SetNillableWarrantyMonths sets the "warranty_months" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableWarrantyMonths(v *int32) *AssetUpdate {
	if v != nil {
		_u.SetWarrantyMonths(*v)
	}
	return _u
}

// AddWarrantyMonths adds value to the "warranty_months" field.
func (_u *AssetUpdate) AddWarrantyMonths(v int32) *AssetUpdate {
	_u.mutation.AddWarrantyMonths(v)
	return _u
}

// ClearWarrantyMonths clears the value of the "warranty_months" field.
func (_u *AssetUpdate) ClearWarrantyMonths() *AssetUpdate {
	_u.mutation.ClearWarrantyMonths()
	return _u
}

// SetPurchaseDate sets the "purchase_date" field.
func (_u *AssetUpdate) SetPurchaseDate(v time.Time) *AssetUpdate {
	_u.mutation.SetPurchaseDate(v)
	return _u
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_u *AssetUpdate) SetNillablePurchaseDate(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetPurchaseDate(*v)
	}
	return _u
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (_u *AssetUpdate) ClearPurchaseDate() *AssetUpdate {
	_u.mutation.ClearPurchaseDate()
	return _u
}

// SetOrderNumber sets the "order_number" field.
func (_u *AssetUpdate) SetOrderNumber(v string) *AssetUpdate {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableOrderNumber(v *string) *AssetUpdate {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// ClearOrderNumber clears the value of the "order_number" field.
func (_u *AssetUpdate) ClearOrderNumber() *AssetUpdate {
	_u.mutation.ClearOrderNumber()
	return _u
}

// SetPurchaseCost sets the "purchase_cost" field.
func (_u *AssetUpdate) SetPurchaseCost(v float64) *AssetUpdate {
	_u.mutation.ResetPurchaseCost()
	_u.mutation.SetPurchaseCost(v)
	return _u
}

// SetNillablePurchaseCost sets the "purchase_cost" field if the given value is not nil.
func (_u *AssetUpdate) SetNillablePurchaseCost(v *float64) *AssetUpdate {
	if v != nil {
		_u.SetPurchaseCost(*v)
	}
	return _u
}

// AddPurchaseCost adds value to the "purchase_cost" field.
func (_u *AssetUpdate) AddPurchaseCost(v float64) *AssetUpdate {
	_u.mutation.AddPurchaseCost(v)
	return _u
}

// ClearPurchaseCost clears the value of the "purchase_cost" field.
func (_u *AssetUpdate) ClearPurchaseCost() *AssetUpdate {
	_u.mutation.ClearPurchaseCost()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AssetUpdate) SetNotes(v string) *AssetUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableNotes(v *string) *AssetUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AssetUpdate) ClearNotes() *AssetUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetTags sets the "tags" field.
func (_u *AssetUpdate) SetTags(v string) *AssetUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableTags(v *string) *AssetUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *AssetUpdate) ClearTags() *AssetUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AssetUpdate) SetMetadata(v string) *AssetUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableMetadata(v *string) *AssetUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AssetUpdate) ClearMetadata() *AssetUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *AssetUpdate) SetCategory(v *Category) *AssetUpdate {
	return _u.SetCategoryID(v.ID)
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_u *AssetUpdate) SetSupplier(v *Supplier) *AssetUpdate {
	return _u.SetSupplierID(v.ID)
}

// SetLocation sets the "location" edge to the Location entity.
func (_u *AssetUpdate) SetLocation(v *Location) *AssetUpdate {
	return _u.SetLocationID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *AssetUpdate) SetEmployee(v *Employee) *AssetUpdate {
	return _u.SetEmployeeID(v.ID)
}

// AddAssignmentIDs adds the "assignments" edge to the AssetAssignment entity by IDs.
func (_u *AssetUpdate) AddAssignmentIDs(ids ...string) *AssetUpdate {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the AssetAssignment entity.
func (_u *AssetUpdate) AddAssignments(v ...*AssetAssignment) *AssetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *AssetUpdate) ClearCategory() *AssetUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearSupplier clears the "supplier" edge to the Supplier entity.
func (_u *AssetUpdate) ClearSupplier() *AssetUpdate {
	_u.mutation.ClearSupplier()
	return _u
}

// ClearLocation clears the "location" edge to the Location entity.
func (_u *AssetUpdate) ClearLocation() *AssetUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *AssetUpdate) ClearEmployee() *AssetUpdate {
	_u.mutation.ClearEmployee()
	return _u
}

// ClearAssignments clears all "assignments" edges to the AssetAssignment entity.
func (_u *AssetUpdate) ClearAssignments() *AssetUpdate {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to AssetAssignment entities by IDs.
func (_u *AssetUpdate) RemoveAssignmentIDs(ids ...string) *AssetUpdate {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to AssetAssignment entities.
func (_u *AssetUpdate) RemoveAssignments(v ...*AssetAssignment) *AssetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdate) check() error {
	if v, ok := _u.mutation.AssetTag(); ok {
		if err := asset.AssetTagValidator(v); err != nil {
			return &ValidationError{Name: "asset_tag", err: fmt.Errorf(`ent: validator failed for field "Asset.asset_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := asset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Asset.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AssetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AssetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(asset.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(asset.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(asset.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(asset.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(asset.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(asset.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(asset.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(asset.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(asset.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(asset.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(asset.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(asset.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AssetTag(); ok {
		_spec.SetField(asset.FieldAssetTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(asset.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(asset.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Serial(); ok {
		_spec.SetField(asset.FieldSerial, field.TypeString, value)
	}
	if _u.mutation.SerialCleared() {
		_spec.ClearField(asset.FieldSerial, field.TypeString)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(asset.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(asset.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelNumber(); ok {
		_spec.SetField(asset.FieldModelNumber, field.TypeString, value)
	}
	if _u.mutation.ModelNumberCleared() {
		_spec.ClearField(asset.FieldModelNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(asset.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(asset.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PhotoKey(); ok {
		_spec.SetField(asset.FieldPhotoKey, field.TypeString, value)
	}
	if _u.mutation.PhotoKeyCleared() {
		_spec.ClearField(asset.FieldPhotoKey, field.TypeString)
	}
	if value, ok := _u.mutation.WarrantyMonths(); ok {
		_spec.SetField(asset.FieldWarrantyMonths, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedWarrantyMonths(); ok {
		_spec.AddField(asset.FieldWarrantyMonths, field.TypeInt32, value)
	}
	if _u.mutation.WarrantyMonthsCleared() {
		_spec.ClearField(asset.FieldWarrantyMonths, field.TypeInt32)
	}
	if value, ok := _u.mutation.PurchaseDate(); ok {
		_spec.SetField(asset.FieldPurchaseDate, field.TypeTime, value)
	}
	if _u.mutation.PurchaseDateCleared() {
		_spec.ClearField(asset.FieldPurchaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(asset.FieldOrderNumber, field.TypeString, value)
	}
	if _u.mutation.OrderNumberCleared() {
		_spec.ClearField(asset.FieldOrderNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PurchaseCost(); ok {
		_spec.SetField(asset.FieldPurchaseCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPurchaseCost(); ok {
		_spec.AddField(asset.FieldPurchaseCost, field.TypeFloat64, value)
	}
	if _u.mutation.PurchaseCostCleared() {
		_spec.ClearField(asset.FieldPurchaseCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(asset.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(asset.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(asset.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(asset.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(asset.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(asset.FieldMetadata, field.TypeString)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.CategoryTable,
			Columns: []string{asset.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.CategoryTable,
			Columns: []string{asset.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupplierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.SupplierTable,
			Columns: []string{asset.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.SupplierTable,
			Columns: []string{asset.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.LocationTable,
			Columns: []string{asset.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.LocationTable,
			Columns: []string{asset.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.EmployeeTable,
			Columns: []string{asset.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.EmployeeTable,
			Columns: []string{asset.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AssignmentsTable,
			Columns: []string{asset.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AssignmentsTable,
			Columns: []string{asset.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AssignmentsTable,
			Columns: []string{asset.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *AssetUpdateOne) SetCreateBy(v uint32) *AssetUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableCreateBy(v *uint32) *AssetUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *AssetUpdateOne) AddCreateBy(v int32) *AssetUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *AssetUpdateOne) ClearCreateBy() *AssetUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *AssetUpdateOne) SetUpdateBy(v uint32) *AssetUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableUpdateBy(v *uint32) *AssetUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *AssetUpdateOne) AddUpdateBy(v int32) *AssetUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *AssetUpdateOne) ClearUpdateBy() *AssetUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AssetUpdateOne) SetUpdateTime(v time.Time) *AssetUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableUpdateTime(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *AssetUpdateOne) ClearUpdateTime() *AssetUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *AssetUpdateOne) SetDeleteTime(v time.Time) *AssetUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableDeleteTime(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *AssetUpdateOne) ClearDeleteTime() *AssetUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetAssetTag sets the "asset_tag" field.
func (_u *AssetUpdateOne) SetAssetTag(v string) *AssetUpdateOne {
	_u.mutation.SetAssetTag(v)
	return _u
}

// SetNillableAssetTag sets the "asset_tag" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableAssetTag(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetAssetTag(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AssetUpdateOne) SetName(v string) *AssetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableName(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *AssetUpdateOne) ClearName() *AssetUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetSerial sets the "serial" field.
func (_u *AssetUpdateOne) SetSerial(v string) *AssetUpdateOne {
	_u.mutation.SetSerial(v)
	return _u
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableSerial(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetSerial(*v)
	}
	return _u
}

// ClearSerial clears the value of the "serial" field.
func (_u *AssetUpdateOne) ClearSerial() *AssetUpdateOne {
	_u.mutation.ClearSerial()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AssetUpdateOne) SetModelName(v string) *AssetUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableModelName(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *AssetUpdateOne) ClearModelName() *AssetUpdateOne {
	_u.mutation.ClearModelName()
	return _u
}

// SetModelNumber sets the "model_number" field.
func (_u *AssetUpdateOne) SetModelNumber(v string) *AssetUpdateOne {
	_u.mutation.SetModelNumber(v)
	return _u
}

// SetNillableModelNumber sets the "model_number" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableModelNumber(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetModelNumber(*v)
	}
	return _u
}

// ClearModelNumber clears the value of the "model_number" field.
func (_u *AssetUpdateOne) ClearModelNumber() *AssetUpdateOne {
	_u.mutation.ClearModelNumber()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *AssetUpdateOne) SetCategoryID(v string) *AssetUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableCategoryID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *AssetUpdateOne) ClearCategoryID() *AssetUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetSupplierID sets the "supplier_id" field.
func (_u *AssetUpdateOne) SetSupplierID(v string) *AssetUpdateOne {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableSupplierID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// ClearSupplierID clears the value of the "supplier_id" field.
func (_u *AssetUpdateOne) ClearSupplierID() *AssetUpdateOne {
	_u.mutation.ClearSupplierID()
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *AssetUpdateOne) SetLocationID(v string) *AssetUpdateOne {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableLocationID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// ClearLocationID clears the value of the "location_id" field.
func (_u *AssetUpdateOne) ClearLocationID() *AssetUpdateOne {
	_u.mutation.ClearLocationID()
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *AssetUpdateOne) SetEmployeeID(v string) *AssetUpdateOne {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableEmployeeID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// ClearEmployeeID clears the value of the "employee_id" field.
func (_u *AssetUpdateOne) ClearEmployeeID() *AssetUpdateOne {
	_u.mutation.ClearEmployeeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AssetUpdateOne) SetStatus(v int32) *AssetUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableStatus(v *int32) *AssetUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AssetUpdateOne) AddStatus(v int32) *AssetUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPhotoKey sets the "photo_key" field.
func (_u *AssetUpdateOne) SetPhotoKey(v string) *AssetUpdateOne {
	_u.mutation.SetPhotoKey(v)
	return _u
}

// SetNillablePhotoKey sets the "photo_key" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillablePhotoKey(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetPhotoKey(*v)
	}
	return _u
}

// ClearPhotoKey clears the value of the "photo_key" field.
func (_u *AssetUpdateOne) ClearPhotoKey() *AssetUpdateOne {
	_u.mutation.ClearPhotoKey()
	return _u
}

// SetWarrantyMonths sets the "warranty_months" field.
func (_u *AssetUpdateOne) SetWarrantyMonths(v int32) *AssetUpdateOne {
	_u.mutation.ResetWarrantyMonths()
	_u.mutation.SetWarrantyMonths(v)
	return _u
}

// SetNillableWarrantyMonths sets the "warranty_months" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableWarrantyMonths(v *int32) *AssetUpdateOne {
	if v != nil {
		_u.SetWarrantyMonths(*v)
	}
	return _u
}

// AddWarrantyMonths adds value to the "warranty_months" field.
func (_u *AssetUpdateOne) AddWarrantyMonths(v int32) *AssetUpdateOne {
	_u.mutation.AddWarrantyMonths(v)
	return _u
}

// ClearWarrantyMonths clears the value of the "warranty_months" field.
func (_u *AssetUpdateOne) ClearWarrantyMonths() *AssetUpdateOne {
	_u.mutation.ClearWarrantyMonths()
	return _u
}

// SetPurchaseDate sets the "purchase_date" field.
func (_u *AssetUpdateOne) SetPurchaseDate(v time.Time) *AssetUpdateOne {
	_u.mutation.SetPurchaseDate(v)
	return _u
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillablePurchaseDate(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetPurchaseDate(*v)
	}
	return _u
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (_u *AssetUpdateOne) ClearPurchaseDate() *AssetUpdateOne {
	_u.mutation.ClearPurchaseDate()
	return _u
}

// SetOrderNumber sets the "order_number" field.
func (_u *AssetUpdateOne) SetOrderNumber(v string) *AssetUpdateOne {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableOrderNumber(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// ClearOrderNumber clears the value of the "order_number" field.
func (_u *AssetUpdateOne) ClearOrderNumber() *AssetUpdateOne {
	_u.mutation.ClearOrderNumber()
	return _u
}

// SetPurchaseCost sets the "purchase_cost" field.
func (_u *AssetUpdateOne) SetPurchaseCost(v float64) *AssetUpdateOne {
	_u.mutation.ResetPurchaseCost()
	_u.mutation.SetPurchaseCost(v)
	return _u
}

// SetNillablePurchaseCost sets the "purchase_cost" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillablePurchaseCost(v *float64) *AssetUpdateOne {
	if v != nil {
		_u.SetPurchaseCost(*v)
	}
	return _u
}

// AddPurchaseCost adds value to the "purchase_cost" field.
func (_u *AssetUpdateOne) AddPurchaseCost(v float64) *AssetUpdateOne {
	_u.mutation.AddPurchaseCost(v)
	return _u
}

// ClearPurchaseCost clears the value of the "purchase_cost" field.
func (_u *AssetUpdateOne) ClearPurchaseCost() *AssetUpdateOne {
	_u.mutation.ClearPurchaseCost()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AssetUpdateOne) SetNotes(v string) *AssetUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableNotes(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AssetUpdateOne) ClearNotes() *AssetUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetTags sets the "tags" field.
func (_u *AssetUpdateOne) SetTags(v string) *AssetUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableTags(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *AssetUpdateOne) ClearTags() *AssetUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AssetUpdateOne) SetMetadata(v string) *AssetUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableMetadata(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AssetUpdateOne) ClearMetadata() *AssetUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *AssetUpdateOne) SetCategory(v *Category) *AssetUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_u *AssetUpdateOne) SetSupplier(v *Supplier) *AssetUpdateOne {
	return _u.SetSupplierID(v.ID)
}

// SetLocation sets the "location" edge to the Location entity.
func (_u *AssetUpdateOne) SetLocation(v *Location) *AssetUpdateOne {
	return _u.SetLocationID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *AssetUpdateOne) SetEmployee(v *Employee) *AssetUpdateOne {
	return _u.SetEmployeeID(v.ID)
}

// AddAssignmentIDs adds the "assignments" edge to the AssetAssignment entity by IDs.
func (_u *AssetUpdateOne) AddAssignmentIDs(ids ...string) *AssetUpdateOne {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the AssetAssignment entity.
func (_u *AssetUpdateOne) AddAssignments(v ...*AssetAssignment) *AssetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *AssetUpdateOne) ClearCategory() *AssetUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearSupplier clears the "supplier" edge to the Supplier entity.
func (_u *AssetUpdateOne) ClearSupplier() *AssetUpdateOne {
	_u.mutation.ClearSupplier()
	return _u
}

// ClearLocation clears the "location" edge to the Location entity.
func (_u *AssetUpdateOne) ClearLocation() *AssetUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *AssetUpdateOne) ClearEmployee() *AssetUpdateOne {
	_u.mutation.ClearEmployee()
	return _u
}

// ClearAssignments clears all "assignments" edges to the AssetAssignment entity.
func (_u *AssetUpdateOne) ClearAssignments() *AssetUpdateOne {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to AssetAssignment entities by IDs.
func (_u *AssetUpdateOne) RemoveAssignmentIDs(ids ...string) *AssetUpdateOne {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to AssetAssignment entities.
func (_u *AssetUpdateOne) RemoveAssignments(v ...*AssetAssignment) *AssetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdateOne) check() error {
	if v, ok := _u.mutation.AssetTag(); ok {
		if err := asset.AssetTagValidator(v); err != nil {
			return &ValidationError{Name: "asset_tag", err: fmt.Errorf(`ent: validator failed for field "Asset.asset_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := asset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Asset.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AssetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AssetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(asset.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(asset.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(asset.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(asset.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(asset.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(asset.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(asset.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(asset.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(asset.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(asset.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(asset.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(asset.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AssetTag(); ok {
		_spec.SetField(asset.FieldAssetTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(asset.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(asset.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Serial(); ok {
		_spec.SetField(asset.FieldSerial, field.TypeString, value)
	}
	if _u.mutation.SerialCleared() {
		_spec.ClearField(asset.FieldSerial, field.TypeString)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(asset.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(asset.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelNumber(); ok {
		_spec.SetField(asset.FieldModelNumber, field.TypeString, value)
	}
	if _u.mutation.ModelNumberCleared() {
		_spec.ClearField(asset.FieldModelNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(asset.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(asset.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PhotoKey(); ok {
		_spec.SetField(asset.FieldPhotoKey, field.TypeString, value)
	}
	if _u.mutation.PhotoKeyCleared() {
		_spec.ClearField(asset.FieldPhotoKey, field.TypeString)
	}
	if value, ok := _u.mutation.WarrantyMonths(); ok {
		_spec.SetField(asset.FieldWarrantyMonths, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedWarrantyMonths(); ok {
		_spec.AddField(asset.FieldWarrantyMonths, field.TypeInt32, value)
	}
	if _u.mutation.WarrantyMonthsCleared() {
		_spec.ClearField(asset.FieldWarrantyMonths, field.TypeInt32)
	}
	if value, ok := _u.mutation.PurchaseDate(); ok {
		_spec.SetField(asset.FieldPurchaseDate, field.TypeTime, value)
	}
	if _u.mutation.PurchaseDateCleared() {
		_spec.ClearField(asset.FieldPurchaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(asset.FieldOrderNumber, field.TypeString, value)
	}
	if _u.mutation.OrderNumberCleared() {
		_spec.ClearField(asset.FieldOrderNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PurchaseCost(); ok {
		_spec.SetField(asset.FieldPurchaseCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPurchaseCost(); ok {
		_spec.AddField(asset.FieldPurchaseCost, field.TypeFloat64, value)
	}
	if _u.mutation.PurchaseCostCleared() {
		_spec.ClearField(asset.FieldPurchaseCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(asset.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(asset.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(asset.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(asset.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(asset.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(asset.FieldMetadata, field.TypeString)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.CategoryTable,
			Columns: []string{asset.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.CategoryTable,
			Columns: []string{asset.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupplierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.SupplierTable,
			Columns: []string{asset.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.SupplierTable,
			Columns: []string{asset.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.LocationTable,
			Columns: []string{asset.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.LocationTable,
			Columns: []string{asset.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.EmployeeTable,
			Columns: []string{asset.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.EmployeeTable,
			Columns: []string{asset.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AssignmentsTable,
			Columns: []string{asset.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AssignmentsTable,
			Columns: []string{asset.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AssignmentsTable,
			Columns: []string{asset.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
