// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/asset"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/assetassignment"
)

// AssetAssignment is the model entity for the AssetAssignment schema.
type AssetAssignment struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// Asset ID
	AssetID string `json:"asset_id,omitempty"`
	// Asset name (denormalized)
	AssetName string `json:"asset_name,omitempty"`
	// Portal user ID
	UserID uint32 `json:"user_id,omitempty"`
	// User display name (denormalized)
	UserName string `json:"user_name,omitempty"`
	// Action: 1=Assigned, 2=Unassigned, 3=Transferred
	Action int32 `json:"action,omitempty"`
	// When the assignment was made
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// When the asset was returned
	ReturnedAt *time.Time `json:"returned_at,omitempty"`
	// User who performed the assignment
	AssignedBy *uint32 `json:"assigned_by,omitempty"`
	// Notes
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssetAssignmentQuery when eager-loading is set.
	Edges        AssetAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AssetAssignmentEdges holds the relations/edges for other nodes in the graph.
type AssetAssignmentEdges struct {
	// Asset holds the value of the asset edge.
	Asset *Asset `json:"asset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetAssignmentEdges) AssetOrErr() (*Asset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AssetAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assetassignment.FieldUserID, assetassignment.FieldAction, assetassignment.FieldAssignedBy:
			values[i] = new(sql.NullInt64)
		case assetassignment.FieldID, assetassignment.FieldAssetID, assetassignment.FieldAssetName, assetassignment.FieldUserName, assetassignment.FieldNotes:
			values[i] = new(sql.NullString)
		case assetassignment.FieldAssignedAt, assetassignment.FieldReturnedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AssetAssignment fields.
func (_m *AssetAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assetassignment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case assetassignment.FieldAssetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				_m.AssetID = value.String
			}
		case assetassignment.FieldAssetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_name", values[i])
			} else if value.Valid {
				_m.AssetName = value.String
			}
		case assetassignment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint32(value.Int64)
			}
		case assetassignment.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case assetassignment.FieldAction:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = int32(value.Int64)
			}
		case assetassignment.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = value.Time
			}
		case assetassignment.FieldReturnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field returned_at", values[i])
			} else if value.Valid {
				_m.ReturnedAt = new(time.Time)
				*_m.ReturnedAt = value.Time
			}
		case assetassignment.FieldAssignedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_by", values[i])
			} else if value.Valid {
				_m.AssignedBy = new(uint32)
				*_m.AssignedBy = uint32(value.Int64)
			}
		case assetassignment.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AssetAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *AssetAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAsset queries the "asset" edge of the AssetAssignment entity.
func (_m *AssetAssignment) QueryAsset() *AssetQuery {
	return NewAssetAssignmentClient(_m.config).QueryAsset(_m)
}

// Update returns a builder for updating this AssetAssignment.
// Note that you need to call AssetAssignment.Unwrap() before calling this method if this AssetAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AssetAssignment) Update() *AssetAssignmentUpdateOne {
	return NewAssetAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AssetAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AssetAssignment) Unwrap() *AssetAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AssetAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AssetAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("AssetAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("asset_id=")
	builder.WriteString(_m.AssetID)
	builder.WriteString(", ")
	builder.WriteString("asset_name=")
	builder.WriteString(_m.AssetName)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(_m.AssignedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReturnedAt; v != nil {
		builder.WriteString("returned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AssignedBy; v != nil {
		builder.WriteString("assigned_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// AssetAssignments is a parsable slice of AssetAssignment.
type AssetAssignments []*AssetAssignment
