// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/asset"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/category"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/location"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/supplier"
)

// Asset is the model entity for the Asset schema.
type Asset struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Asset tag (unique per tenant)
	AssetTag string `json:"asset_tag,omitempty"`
	// Asset name
	Name string `json:"name,omitempty"`
	// Serial number
	Serial string `json:"serial,omitempty"`
	// Model name
	ModelName string `json:"model_name,omitempty"`
	// Model number
	ModelNumber string `json:"model_number,omitempty"`
	// Category ID
	CategoryID string `json:"category_id,omitempty"`
	// Supplier ID
	SupplierID string `json:"supplier_id,omitempty"`
	// Location ID (when unassigned)
	LocationID string `json:"location_id,omitempty"`
	// Portal user ID (when assigned)
	UserID *uint32 `json:"user_id,omitempty"`
	// Asset status: 1=Deployable, 2=Assigned, 3=Broken, 4=Archived
	Status int32 `json:"status,omitempty"`
	// Photo storage key in S3
	PhotoKey string `json:"photo_key,omitempty"`
	// Warranty duration in months
	WarrantyMonths *int32 `json:"warranty_months,omitempty"`
	// Purchase date
	PurchaseDate *time.Time `json:"purchase_date,omitempty"`
	// Order number
	OrderNumber string `json:"order_number,omitempty"`
	// Purchase cost
	PurchaseCost *float64 `json:"purchase_cost,omitempty"`
	// Notes
	Notes string `json:"notes,omitempty"`
	// Salvage value
	SalvageValue *float64 `json:"salvage_value,omitempty"`
	// Useful life in years
	UsefulLifeYears *int32 `json:"useful_life_years,omitempty"`
	// Depreciation rate for DDB calculation
	DepreciationRate *float64 `json:"depreciation_rate,omitempty"`
	// Custom tags (JSON)
	Tags string `json:"tags,omitempty"`
	// Custom metadata (JSON)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssetQuery when eager-loading is set.
	Edges        AssetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AssetEdges holds the relations/edges for other nodes in the graph.
type AssetEdges struct {
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// Supplier holds the value of the supplier edge.
	Supplier *Supplier `json:"supplier,omitempty"`
	// Location holds the value of the location edge.
	Location *Location `json:"location,omitempty"`
	// Assignments holds the value of the assignments edge.
	Assignments []*AssetAssignment `json:"assignments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// SupplierOrErr returns the Supplier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetEdges) SupplierOrErr() (*Supplier, error) {
	if e.Supplier != nil {
		return e.Supplier, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: supplier.Label}
	}
	return nil, &NotLoadedError{edge: "supplier"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetEdges) LocationOrErr() (*Location, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: location.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// AssignmentsOrErr returns the Assignments value or an error if the edge
// was not loaded in eager-loading.
func (e AssetEdges) AssignmentsOrErr() ([]*AssetAssignment, error) {
	if e.loadedTypes[3] {
		return e.Assignments, nil
	}
	return nil, &NotLoadedError{edge: "assignments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Asset) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case asset.FieldMetadata:
			values[i] = new([]byte)
		case asset.FieldPurchaseCost, asset.FieldSalvageValue, asset.FieldDepreciationRate:
			values[i] = new(sql.NullFloat64)
		case asset.FieldCreateBy, asset.FieldUpdateBy, asset.FieldTenantID, asset.FieldUserID, asset.FieldStatus, asset.FieldWarrantyMonths, asset.FieldUsefulLifeYears:
			values[i] = new(sql.NullInt64)
		case asset.FieldID, asset.FieldAssetTag, asset.FieldName, asset.FieldSerial, asset.FieldModelName, asset.FieldModelNumber, asset.FieldCategoryID, asset.FieldSupplierID, asset.FieldLocationID, asset.FieldPhotoKey, asset.FieldOrderNumber, asset.FieldNotes, asset.FieldTags:
			values[i] = new(sql.NullString)
		case asset.FieldCreateTime, asset.FieldUpdateTime, asset.FieldDeleteTime, asset.FieldPurchaseDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Asset fields.
func (_m *Asset) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case asset.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case asset.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case asset.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case asset.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case asset.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case asset.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case asset.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case asset.FieldAssetTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_tag", values[i])
			} else if value.Valid {
				_m.AssetTag = value.String
			}
		case asset.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case asset.FieldSerial:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field serial", values[i])
			} else if value.Valid {
				_m.Serial = value.String
			}
		case asset.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case asset.FieldModelNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_number", values[i])
			} else if value.Valid {
				_m.ModelNumber = value.String
			}
		case asset.FieldCategoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = value.String
			}
		case asset.FieldSupplierID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_id", values[i])
			} else if value.Valid {
				_m.SupplierID = value.String
			}
		case asset.FieldLocationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location_id", values[i])
			} else if value.Valid {
				_m.LocationID = value.String
			}
		case asset.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uint32)
				*_m.UserID = uint32(value.Int64)
			}
		case asset.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int32(value.Int64)
			}
		case asset.FieldPhotoKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field photo_key", values[i])
			} else if value.Valid {
				_m.PhotoKey = value.String
			}
		case asset.FieldWarrantyMonths:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field warranty_months", values[i])
			} else if value.Valid {
				_m.WarrantyMonths = new(int32)
				*_m.WarrantyMonths = int32(value.Int64)
			}
		case asset.FieldPurchaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_date", values[i])
			} else if value.Valid {
				_m.PurchaseDate = new(time.Time)
				*_m.PurchaseDate = value.Time
			}
		case asset.FieldOrderNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_number", values[i])
			} else if value.Valid {
				_m.OrderNumber = value.String
			}
		case asset.FieldPurchaseCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_cost", values[i])
			} else if value.Valid {
				_m.PurchaseCost = new(float64)
				*_m.PurchaseCost = value.Float64
			}
		case asset.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case asset.FieldSalvageValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field salvage_value", values[i])
			} else if value.Valid {
				_m.SalvageValue = new(float64)
				*_m.SalvageValue = value.Float64
			}
		case asset.FieldUsefulLifeYears:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field useful_life_years", values[i])
			} else if value.Valid {
				_m.UsefulLifeYears = new(int32)
				*_m.UsefulLifeYears = int32(value.Int64)
			}
		case asset.FieldDepreciationRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field depreciation_rate", values[i])
			} else if value.Valid {
				_m.DepreciationRate = new(float64)
				*_m.DepreciationRate = value.Float64
			}
		case asset.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				_m.Tags = value.String
			}
		case asset.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Asset.
// This includes values selected through modifiers, order, etc.
func (_m *Asset) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the Asset entity.
func (_m *Asset) QueryCategory() *CategoryQuery {
	return NewAssetClient(_m.config).QueryCategory(_m)
}

// QuerySupplier queries the "supplier" edge of the Asset entity.
func (_m *Asset) QuerySupplier() *SupplierQuery {
	return NewAssetClient(_m.config).QuerySupplier(_m)
}

// QueryLocation queries the "location" edge of the Asset entity.
func (_m *Asset) QueryLocation() *LocationQuery {
	return NewAssetClient(_m.config).QueryLocation(_m)
}

// QueryAssignments queries the "assignments" edge of the Asset entity.
func (_m *Asset) QueryAssignments() *AssetAssignmentQuery {
	return NewAssetClient(_m.config).QueryAssignments(_m)
}

// Update returns a builder for updating this Asset.
// Note that you need to call Asset.Unwrap() before calling this method if this Asset
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Asset) Update() *AssetUpdateOne {
	return NewAssetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Asset entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Asset) Unwrap() *Asset {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Asset is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Asset) String() string {
	var builder strings.Builder
	builder.WriteString("Asset(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("asset_tag=")
	builder.WriteString(_m.AssetTag)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("serial=")
	builder.WriteString(_m.Serial)
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	builder.WriteString("model_number=")
	builder.WriteString(_m.ModelNumber)
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(_m.CategoryID)
	builder.WriteString(", ")
	builder.WriteString("supplier_id=")
	builder.WriteString(_m.SupplierID)
	builder.WriteString(", ")
	builder.WriteString("location_id=")
	builder.WriteString(_m.LocationID)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("photo_key=")
	builder.WriteString(_m.PhotoKey)
	builder.WriteString(", ")
	if v := _m.WarrantyMonths; v != nil {
		builder.WriteString("warranty_months=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PurchaseDate; v != nil {
		builder.WriteString("purchase_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("order_number=")
	builder.WriteString(_m.OrderNumber)
	builder.WriteString(", ")
	if v := _m.PurchaseCost; v != nil {
		builder.WriteString("purchase_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	if v := _m.SalvageValue; v != nil {
		builder.WriteString("salvage_value=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UsefulLifeYears; v != nil {
		builder.WriteString("useful_life_years=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DepreciationRate; v != nil {
		builder.WriteString("depreciation_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(_m.Tags)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// Assets is a parsable slice of Asset.
type Assets []*Asset
