// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/asset"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/assetassignment"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/employee"
)

// AssetAssignmentCreate is the builder for creating a AssetAssignment entity.
type AssetAssignmentCreate struct {
	config
	mutation *AssetAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAssetID sets the "asset_id" field.
func (_c *AssetAssignmentCreate) SetAssetID(v string) *AssetAssignmentCreate {
	_c.mutation.SetAssetID(v)
	return _c
}

// SetAssetName sets the "asset_name" field.
func (_c *AssetAssignmentCreate) SetAssetName(v string) *AssetAssignmentCreate {
	_c.mutation.SetAssetName(v)
	return _c
}

// SetNillableAssetName sets the "asset_name" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableAssetName(v *string) *AssetAssignmentCreate {
	if v != nil {
		_c.SetAssetName(*v)
	}
	return _c
}

// SetEmployeeID sets the "employee_id" field.
func (_c *AssetAssignmentCreate) SetEmployeeID(v string) *AssetAssignmentCreate {
	_c.mutation.SetEmployeeID(v)
	return _c
}

// SetEmployeeName sets the "employee_name" field.
func (_c *AssetAssignmentCreate) SetEmployeeName(v string) *AssetAssignmentCreate {
	_c.mutation.SetEmployeeName(v)
	return _c
}

// SetNillableEmployeeName sets the "employee_name" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableEmployeeName(v *string) *AssetAssignmentCreate {
	if v != nil {
		_c.SetEmployeeName(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AssetAssignmentCreate) SetAction(v int32) *AssetAssignmentCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableAction(v *int32) *AssetAssignmentCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *AssetAssignmentCreate) SetAssignedAt(v time.Time) *AssetAssignmentCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetReturnedAt sets the "returned_at" field.
func (_c *AssetAssignmentCreate) SetReturnedAt(v time.Time) *AssetAssignmentCreate {
	_c.mutation.SetReturnedAt(v)
	return _c
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableReturnedAt(v *time.Time) *AssetAssignmentCreate {
	if v != nil {
		_c.SetReturnedAt(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *AssetAssignmentCreate) SetAssignedBy(v uint32) *AssetAssignmentCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableAssignedBy(v *uint32) *AssetAssignmentCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *AssetAssignmentCreate) SetNotes(v string) *AssetAssignmentCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableNotes(v *string) *AssetAssignmentCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AssetAssignmentCreate) SetID(v string) *AssetAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_c *AssetAssignmentCreate) SetAsset(v *Asset) *AssetAssignmentCreate {
	return _c.SetAssetID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *AssetAssignmentCreate) SetEmployee(v *Employee) *AssetAssignmentCreate {
	return _c.SetEmployeeID(v.ID)
}

// Mutation returns the AssetAssignmentMutation object of the builder.
func (_c *AssetAssignmentCreate) Mutation() *AssetAssignmentMutation {
	return _c.mutation
}

// Save creates the AssetAssignment in the database.
func (_c *AssetAssignmentCreate) Save(ctx context.Context) (*AssetAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetAssignmentCreate) SaveX(ctx context.Context) *AssetAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetAssignmentCreate) defaults() {
	if _, ok := _c.mutation.Action(); !ok {
		v := assetassignment.DefaultAction
		_c.mutation.SetAction(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetAssignmentCreate) check() error {
	if _, ok := _c.mutation.AssetID(); !ok {
		return &ValidationError{Name: "asset_id", err: errors.New(`ent: missing required field "AssetAssignment.asset_id"`)}
	}
	if v, ok := _c.mutation.AssetID(); ok {
		if err := assetassignment.AssetIDValidator(v); err != nil {
			return &ValidationError{Name: "asset_id", err: fmt.Errorf(`ent: validator failed for field "AssetAssignment.asset_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`ent: missing required field "AssetAssignment.employee_id"`)}
	}
	if v, ok := _c.mutation.EmployeeID(); ok {
		if err := assetassignment.EmployeeIDValidator(v); err != nil {
			return &ValidationError{Name: "employee_id", err: fmt.Errorf(`ent: validator failed for field "AssetAssignment.employee_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AssetAssignment.action"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "AssetAssignment.assigned_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := assetassignment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AssetAssignment.id": %w`, err)}
		}
	}
	if len(_c.mutation.AssetIDs()) == 0 {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required edge "AssetAssignment.asset"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "AssetAssignment.employee"`)}
	}
	return nil
}

func (_c *AssetAssignmentCreate) sqlSave(ctx context.Context) (*AssetAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AssetAssignment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetAssignmentCreate) createSpec() (*AssetAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assetassignment.Table, sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AssetName(); ok {
		_spec.SetField(assetassignment.FieldAssetName, field.TypeString, value)
		_node.AssetName = value
	}
	if value, ok := _c.mutation.EmployeeName(); ok {
		_spec.SetField(assetassignment.FieldEmployeeName, field.TypeString, value)
		_node.EmployeeName = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(assetassignment.FieldAction, field.TypeInt32, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(assetassignment.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.ReturnedAt(); ok {
		_spec.SetField(assetassignment.FieldReturnedAt, field.TypeTime, value)
		_node.ReturnedAt = &value
	}
	if value, ok := _c.mutation.AssignedBy(); ok {
		_spec.SetField(assetassignment.FieldAssignedBy, field.TypeUint32, value)
		_node.AssignedBy = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(assetassignment.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := _c.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assetassignment.AssetTable,
			Columns: []string{assetassignment.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   assetassignment.EmployeeTable,
			Columns: []string{assetassignment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AssetAssignment.Create().
//		SetAssetID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetAssignmentUpsert) {
//			SetAssetID(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *AssetAssignmentUpsertOne {
	_c.conflict = opts
	return &AssetAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AssetAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetAssignmentCreate) OnConflictColumns(columns ...string) *AssetAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// AssetAssignmentUpsertOne is the builder for "upsert"-ing
	//  one AssetAssignment node.
	AssetAssignmentUpsertOne struct {
		create *AssetAssignmentCreate
	}

	// AssetAssignmentUpsert is the "OnConflict" setter.
	AssetAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetAssetID sets the "asset_id" field.
func (u *AssetAssignmentUpsert) SetAssetID(v string) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldAssetID, v)
	return u
}

// UpdateAssetID sets the "asset_id" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateAssetID() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldAssetID)
	return u
}

// SetAssetName sets the "asset_name" field.
func (u *AssetAssignmentUpsert) SetAssetName(v string) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldAssetName, v)
	return u
}

// UpdateAssetName sets the "asset_name" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateAssetName() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldAssetName)
	return u
}

// ClearAssetName clears the value of the "asset_name" field.
func (u *AssetAssignmentUpsert) ClearAssetName() *AssetAssignmentUpsert {
	u.SetNull(assetassignment.FieldAssetName)
	return u
}

// SetEmployeeID sets the "employee_id" field.
func (u *AssetAssignmentUpsert) SetEmployeeID(v string) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldEmployeeID, v)
	return u
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateEmployeeID() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldEmployeeID)
	return u
}

// SetEmployeeName sets the "employee_name" field.
func (u *AssetAssignmentUpsert) SetEmployeeName(v string) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldEmployeeName, v)
	return u
}

// UpdateEmployeeName sets the "employee_name" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateEmployeeName() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldEmployeeName)
	return u
}

// ClearEmployeeName clears the value of the "employee_name" field.
func (u *AssetAssignmentUpsert) ClearEmployeeName() *AssetAssignmentUpsert {
	u.SetNull(assetassignment.FieldEmployeeName)
	return u
}

// SetAction sets the "action" field.
func (u *AssetAssignmentUpsert) SetAction(v int32) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateAction() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldAction)
	return u
}

// AddAction adds v to the "action" field.
func (u *AssetAssignmentUpsert) AddAction(v int32) *AssetAssignmentUpsert {
	u.Add(assetassignment.FieldAction, v)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *AssetAssignmentUpsert) SetAssignedAt(v time.Time) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateAssignedAt() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldAssignedAt)
	return u
}

// SetReturnedAt sets the "returned_at" field.
func (u *AssetAssignmentUpsert) SetReturnedAt(v time.Time) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldReturnedAt, v)
	return u
}

// UpdateReturnedAt sets the "returned_at" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateReturnedAt() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldReturnedAt)
	return u
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (u *AssetAssignmentUpsert) ClearReturnedAt() *AssetAssignmentUpsert {
	u.SetNull(assetassignment.FieldReturnedAt)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *AssetAssignmentUpsert) SetAssignedBy(v uint32) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateAssignedBy() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldAssignedBy)
	return u
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *AssetAssignmentUpsert) AddAssignedBy(v uint32) *AssetAssignmentUpsert {
	u.Add(assetassignment.FieldAssignedBy, v)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *AssetAssignmentUpsert) ClearAssignedBy() *AssetAssignmentUpsert {
	u.SetNull(assetassignment.FieldAssignedBy)
	return u
}

// SetNotes sets the "notes" field.
func (u *AssetAssignmentUpsert) SetNotes(v string) *AssetAssignmentUpsert {
	u.Set(assetassignment.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AssetAssignmentUpsert) UpdateNotes() *AssetAssignmentUpsert {
	u.SetExcluded(assetassignment.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *AssetAssignmentUpsert) ClearNotes() *AssetAssignmentUpsert {
	u.SetNull(assetassignment.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AssetAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(assetassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AssetAssignmentUpsertOne) UpdateNewValues() *AssetAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(assetassignment.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AssetAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AssetAssignmentUpsertOne) Ignore() *AssetAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetAssignmentUpsertOne) DoNothing() *AssetAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetAssignmentCreate.OnConflict
// documentation for more info.
func (u *AssetAssignmentUpsertOne) Update(set func(*AssetAssignmentUpsert)) *AssetAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetAssetID sets the "asset_id" field.
func (u *AssetAssignmentUpsertOne) SetAssetID(v string) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssetID(v)
	})
}

// UpdateAssetID sets the "asset_id" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateAssetID() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssetID()
	})
}

// SetAssetName sets the "asset_name" field.
func (u *AssetAssignmentUpsertOne) SetAssetName(v string) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssetName(v)
	})
}

// UpdateAssetName sets the "asset_name" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateAssetName() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssetName()
	})
}

// ClearAssetName clears the value of the "asset_name" field.
func (u *AssetAssignmentUpsertOne) ClearAssetName() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearAssetName()
	})
}

// SetEmployeeID sets the "employee_id" field.
func (u *AssetAssignmentUpsertOne) SetEmployeeID(v string) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetEmployeeID(v)
	})
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateEmployeeID() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateEmployeeID()
	})
}

// SetEmployeeName sets the "employee_name" field.
func (u *AssetAssignmentUpsertOne) SetEmployeeName(v string) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetEmployeeName(v)
	})
}

// UpdateEmployeeName sets the "employee_name" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateEmployeeName() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateEmployeeName()
	})
}

// ClearEmployeeName clears the value of the "employee_name" field.
func (u *AssetAssignmentUpsertOne) ClearEmployeeName() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearEmployeeName()
	})
}

// SetAction sets the "action" field.
func (u *AssetAssignmentUpsertOne) SetAction(v int32) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAction(v)
	})
}

// AddAction adds v to the "action" field.
func (u *AssetAssignmentUpsertOne) AddAction(v int32) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.AddAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateAction() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAction()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *AssetAssignmentUpsertOne) SetAssignedAt(v time.Time) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateAssignedAt() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetReturnedAt sets the "returned_at" field.
func (u *AssetAssignmentUpsertOne) SetReturnedAt(v time.Time) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetReturnedAt(v)
	})
}

// UpdateReturnedAt sets the "returned_at" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateReturnedAt() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateReturnedAt()
	})
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (u *AssetAssignmentUpsertOne) ClearReturnedAt() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearReturnedAt()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *AssetAssignmentUpsertOne) SetAssignedBy(v uint32) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *AssetAssignmentUpsertOne) AddAssignedBy(v uint32) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateAssignedBy() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *AssetAssignmentUpsertOne) ClearAssignedBy() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearAssignedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *AssetAssignmentUpsertOne) SetNotes(v string) *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AssetAssignmentUpsertOne) UpdateNotes() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AssetAssignmentUpsertOne) ClearNotes() *AssetAssignmentUpsertOne {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *AssetAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AssetAssignmentUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AssetAssignmentUpsertOne.ID is not supported by MySQL driver. Use AssetAssignmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AssetAssignmentUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AssetAssignmentCreateBulk is the builder for creating many AssetAssignment entities in bulk.
type AssetAssignmentCreateBulk struct {
	config
	err      error
	builders []*AssetAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the AssetAssignment entities in the database.
func (_c *AssetAssignmentCreateBulk) Save(ctx context.Context) ([]*AssetAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AssetAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetAssignmentCreateBulk) SaveX(ctx context.Context) []*AssetAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AssetAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetAssignmentUpsert) {
//			SetAssetID(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *AssetAssignmentUpsertBulk {
	_c.conflict = opts
	return &AssetAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AssetAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetAssignmentCreateBulk) OnConflictColumns(columns ...string) *AssetAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetAssignmentUpsertBulk{
		create: _c,
	}
}

// AssetAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of AssetAssignment nodes.
type AssetAssignmentUpsertBulk struct {
	create *AssetAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AssetAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(assetassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AssetAssignmentUpsertBulk) UpdateNewValues() *AssetAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(assetassignment.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AssetAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AssetAssignmentUpsertBulk) Ignore() *AssetAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetAssignmentUpsertBulk) DoNothing() *AssetAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *AssetAssignmentUpsertBulk) Update(set func(*AssetAssignmentUpsert)) *AssetAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetAssetID sets the "asset_id" field.
func (u *AssetAssignmentUpsertBulk) SetAssetID(v string) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssetID(v)
	})
}

// UpdateAssetID sets the "asset_id" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateAssetID() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssetID()
	})
}

// SetAssetName sets the "asset_name" field.
func (u *AssetAssignmentUpsertBulk) SetAssetName(v string) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssetName(v)
	})
}

// UpdateAssetName sets the "asset_name" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateAssetName() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssetName()
	})
}

// ClearAssetName clears the value of the "asset_name" field.
func (u *AssetAssignmentUpsertBulk) ClearAssetName() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearAssetName()
	})
}

// SetEmployeeID sets the "employee_id" field.
func (u *AssetAssignmentUpsertBulk) SetEmployeeID(v string) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetEmployeeID(v)
	})
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateEmployeeID() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateEmployeeID()
	})
}

// SetEmployeeName sets the "employee_name" field.
func (u *AssetAssignmentUpsertBulk) SetEmployeeName(v string) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetEmployeeName(v)
	})
}

// UpdateEmployeeName sets the "employee_name" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateEmployeeName() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateEmployeeName()
	})
}

// ClearEmployeeName clears the value of the "employee_name" field.
func (u *AssetAssignmentUpsertBulk) ClearEmployeeName() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearEmployeeName()
	})
}

// SetAction sets the "action" field.
func (u *AssetAssignmentUpsertBulk) SetAction(v int32) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAction(v)
	})
}

// AddAction adds v to the "action" field.
func (u *AssetAssignmentUpsertBulk) AddAction(v int32) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.AddAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateAction() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAction()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *AssetAssignmentUpsertBulk) SetAssignedAt(v time.Time) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateAssignedAt() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetReturnedAt sets the "returned_at" field.
func (u *AssetAssignmentUpsertBulk) SetReturnedAt(v time.Time) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetReturnedAt(v)
	})
}

// UpdateReturnedAt sets the "returned_at" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateReturnedAt() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateReturnedAt()
	})
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (u *AssetAssignmentUpsertBulk) ClearReturnedAt() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearReturnedAt()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *AssetAssignmentUpsertBulk) SetAssignedBy(v uint32) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *AssetAssignmentUpsertBulk) AddAssignedBy(v uint32) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateAssignedBy() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *AssetAssignmentUpsertBulk) ClearAssignedBy() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearAssignedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *AssetAssignmentUpsertBulk) SetNotes(v string) *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AssetAssignmentUpsertBulk) UpdateNotes() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AssetAssignmentUpsertBulk) ClearNotes() *AssetAssignmentUpsertBulk {
	return u.Update(func(s *AssetAssignmentUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *AssetAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AssetAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
