// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/assetdocument"
)

// AssetDocumentCreate is the builder for creating a AssetDocument entity.
type AssetDocumentCreate struct {
	config
	mutation *AssetDocumentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *AssetDocumentCreate) SetCreateTime(v time.Time) *AssetDocumentCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableCreateTime(v *time.Time) *AssetDocumentCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *AssetDocumentCreate) SetUpdateTime(v time.Time) *AssetDocumentCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableUpdateTime(v *time.Time) *AssetDocumentCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *AssetDocumentCreate) SetDeleteTime(v time.Time) *AssetDocumentCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableDeleteTime(v *time.Time) *AssetDocumentCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *AssetDocumentCreate) SetEntityType(v string) *AssetDocumentCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *AssetDocumentCreate) SetEntityID(v string) *AssetDocumentCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *AssetDocumentCreate) SetFileName(v string) *AssetDocumentCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *AssetDocumentCreate) SetFileSize(v int64) *AssetDocumentCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableFileSize(v *int64) *AssetDocumentCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *AssetDocumentCreate) SetMimeType(v string) *AssetDocumentCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableMimeType(v *string) *AssetDocumentCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *AssetDocumentCreate) SetStorageKey(v string) *AssetDocumentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *AssetDocumentCreate) SetChecksum(v string) *AssetDocumentCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableChecksum(v *string) *AssetDocumentCreate {
	if v != nil {
		_c.SetChecksum(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *AssetDocumentCreate) SetDescription(v string) *AssetDocumentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableDescription(v *string) *AssetDocumentCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetUploadedBy sets the "uploaded_by" field.
func (_c *AssetDocumentCreate) SetUploadedBy(v uint32) *AssetDocumentCreate {
	_c.mutation.SetUploadedBy(v)
	return _c
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_c *AssetDocumentCreate) SetNillableUploadedBy(v *uint32) *AssetDocumentCreate {
	if v != nil {
		_c.SetUploadedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AssetDocumentCreate) SetID(v string) *AssetDocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AssetDocumentMutation object of the builder.
func (_c *AssetDocumentCreate) Mutation() *AssetDocumentMutation {
	return _c.mutation
}

// Save creates the AssetDocument in the database.
func (_c *AssetDocumentCreate) Save(ctx context.Context) (*AssetDocument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetDocumentCreate) SaveX(ctx context.Context) *AssetDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetDocumentCreate) defaults() {
	if _, ok := _c.mutation.FileSize(); !ok {
		v := assetdocument.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetDocumentCreate) check() error {
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "AssetDocument.entity_type"`)}
	}
	if v, ok := _c.mutation.EntityType(); ok {
		if err := assetdocument.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "AssetDocument.entity_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "AssetDocument.entity_id"`)}
	}
	if v, ok := _c.mutation.EntityID(); ok {
		if err := assetdocument.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "AssetDocument.entity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "AssetDocument.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := assetdocument.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "AssetDocument.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "AssetDocument.file_size"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "AssetDocument.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := assetdocument.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "AssetDocument.storage_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := assetdocument.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AssetDocument.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AssetDocumentCreate) sqlSave(ctx context.Context) (*AssetDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AssetDocument.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetDocumentCreate) createSpec() (*AssetDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assetdocument.Table, sqlgraph.NewFieldSpec(assetdocument.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(assetdocument.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(assetdocument.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(assetdocument.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(assetdocument.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(assetdocument.FieldEntityID, field.TypeString, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(assetdocument.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(assetdocument.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(assetdocument.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(assetdocument.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(assetdocument.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(assetdocument.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.UploadedBy(); ok {
		_spec.SetField(assetdocument.FieldUploadedBy, field.TypeUint32, value)
		_node.UploadedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AssetDocument.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetDocumentUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetDocumentCreate) OnConflict(opts ...sql.ConflictOption) *AssetDocumentUpsertOne {
	_c.conflict = opts
	return &AssetDocumentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AssetDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetDocumentCreate) OnConflictColumns(columns ...string) *AssetDocumentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetDocumentUpsertOne{
		create: _c,
	}
}

type (
	// AssetDocumentUpsertOne is the builder for "upsert"-ing
	//  one AssetDocument node.
	AssetDocumentUpsertOne struct {
		create *AssetDocumentCreate
	}

	// AssetDocumentUpsert is the "OnConflict" setter.
	AssetDocumentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *AssetDocumentUpsert) SetUpdateTime(v time.Time) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateUpdateTime() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *AssetDocumentUpsert) ClearUpdateTime() *AssetDocumentUpsert {
	u.SetNull(assetdocument.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *AssetDocumentUpsert) SetDeleteTime(v time.Time) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateDeleteTime() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *AssetDocumentUpsert) ClearDeleteTime() *AssetDocumentUpsert {
	u.SetNull(assetdocument.FieldDeleteTime)
	return u
}

// SetEntityType sets the "entity_type" field.
func (u *AssetDocumentUpsert) SetEntityType(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldEntityType, v)
	return u
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateEntityType() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldEntityType)
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *AssetDocumentUpsert) SetEntityID(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateEntityID() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldEntityID)
	return u
}

// SetFileName sets the "file_name" field.
func (u *AssetDocumentUpsert) SetFileName(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateFileName() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldFileName)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *AssetDocumentUpsert) SetFileSize(v int64) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateFileSize() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *AssetDocumentUpsert) AddFileSize(v int64) *AssetDocumentUpsert {
	u.Add(assetdocument.FieldFileSize, v)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *AssetDocumentUpsert) SetMimeType(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateMimeType() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldMimeType)
	return u
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AssetDocumentUpsert) ClearMimeType() *AssetDocumentUpsert {
	u.SetNull(assetdocument.FieldMimeType)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *AssetDocumentUpsert) SetStorageKey(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateStorageKey() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldStorageKey)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *AssetDocumentUpsert) SetChecksum(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateChecksum() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldChecksum)
	return u
}

// ClearChecksum clears the value of the "checksum" field.
func (u *AssetDocumentUpsert) ClearChecksum() *AssetDocumentUpsert {
	u.SetNull(assetdocument.FieldChecksum)
	return u
}

// SetDescription sets the "description" field.
func (u *AssetDocumentUpsert) SetDescription(v string) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateDescription() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AssetDocumentUpsert) ClearDescription() *AssetDocumentUpsert {
	u.SetNull(assetdocument.FieldDescription)
	return u
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *AssetDocumentUpsert) SetUploadedBy(v uint32) *AssetDocumentUpsert {
	u.Set(assetdocument.FieldUploadedBy, v)
	return u
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *AssetDocumentUpsert) UpdateUploadedBy() *AssetDocumentUpsert {
	u.SetExcluded(assetdocument.FieldUploadedBy)
	return u
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *AssetDocumentUpsert) AddUploadedBy(v uint32) *AssetDocumentUpsert {
	u.Add(assetdocument.FieldUploadedBy, v)
	return u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *AssetDocumentUpsert) ClearUploadedBy() *AssetDocumentUpsert {
	u.SetNull(assetdocument.FieldUploadedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AssetDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(assetdocument.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AssetDocumentUpsertOne) UpdateNewValues() *AssetDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(assetdocument.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(assetdocument.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AssetDocument.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AssetDocumentUpsertOne) Ignore() *AssetDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetDocumentUpsertOne) DoNothing() *AssetDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetDocumentCreate.OnConflict
// documentation for more info.
func (u *AssetDocumentUpsertOne) Update(set func(*AssetDocumentUpsert)) *AssetDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *AssetDocumentUpsertOne) SetUpdateTime(v time.Time) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateUpdateTime() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *AssetDocumentUpsertOne) ClearUpdateTime() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *AssetDocumentUpsertOne) SetDeleteTime(v time.Time) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateDeleteTime() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *AssetDocumentUpsertOne) ClearDeleteTime() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearDeleteTime()
	})
}

// SetEntityType sets the "entity_type" field.
func (u *AssetDocumentUpsertOne) SetEntityType(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateEntityType() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateEntityType()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *AssetDocumentUpsertOne) SetEntityID(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateEntityID() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateEntityID()
	})
}

// SetFileName sets the "file_name" field.
func (u *AssetDocumentUpsertOne) SetFileName(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateFileName() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateFileName()
	})
}

// SetFileSize sets the "file_size" field.
func (u *AssetDocumentUpsertOne) SetFileSize(v int64) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *AssetDocumentUpsertOne) AddFileSize(v int64) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateFileSize() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateFileSize()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *AssetDocumentUpsertOne) SetMimeType(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateMimeType() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AssetDocumentUpsertOne) ClearMimeType() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearMimeType()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *AssetDocumentUpsertOne) SetStorageKey(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateStorageKey() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetChecksum sets the "checksum" field.
func (u *AssetDocumentUpsertOne) SetChecksum(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateChecksum() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateChecksum()
	})
}

// ClearChecksum clears the value of the "checksum" field.
func (u *AssetDocumentUpsertOne) ClearChecksum() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearChecksum()
	})
}

// SetDescription sets the "description" field.
func (u *AssetDocumentUpsertOne) SetDescription(v string) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateDescription() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AssetDocumentUpsertOne) ClearDescription() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearDescription()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *AssetDocumentUpsertOne) SetUploadedBy(v uint32) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetUploadedBy(v)
	})
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *AssetDocumentUpsertOne) AddUploadedBy(v uint32) *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.AddUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *AssetDocumentUpsertOne) UpdateUploadedBy() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateUploadedBy()
	})
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *AssetDocumentUpsertOne) ClearUploadedBy() *AssetDocumentUpsertOne {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearUploadedBy()
	})
}

// Exec executes the query.
func (u *AssetDocumentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetDocumentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetDocumentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AssetDocumentUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AssetDocumentUpsertOne.ID is not supported by MySQL driver. Use AssetDocumentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AssetDocumentUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AssetDocumentCreateBulk is the builder for creating many AssetDocument entities in bulk.
type AssetDocumentCreateBulk struct {
	config
	err      error
	builders []*AssetDocumentCreate
	conflict []sql.ConflictOption
}

// Save creates the AssetDocument entities in the database.
func (_c *AssetDocumentCreateBulk) Save(ctx context.Context) ([]*AssetDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AssetDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetDocumentCreateBulk) SaveX(ctx context.Context) []*AssetDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AssetDocument.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetDocumentUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetDocumentCreateBulk) OnConflict(opts ...sql.ConflictOption) *AssetDocumentUpsertBulk {
	_c.conflict = opts
	return &AssetDocumentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AssetDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetDocumentCreateBulk) OnConflictColumns(columns ...string) *AssetDocumentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetDocumentUpsertBulk{
		create: _c,
	}
}

// AssetDocumentUpsertBulk is the builder for "upsert"-ing
// a bulk of AssetDocument nodes.
type AssetDocumentUpsertBulk struct {
	create *AssetDocumentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AssetDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(assetdocument.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AssetDocumentUpsertBulk) UpdateNewValues() *AssetDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(assetdocument.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(assetdocument.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AssetDocument.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AssetDocumentUpsertBulk) Ignore() *AssetDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetDocumentUpsertBulk) DoNothing() *AssetDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetDocumentCreateBulk.OnConflict
// documentation for more info.
func (u *AssetDocumentUpsertBulk) Update(set func(*AssetDocumentUpsert)) *AssetDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *AssetDocumentUpsertBulk) SetUpdateTime(v time.Time) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateUpdateTime() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *AssetDocumentUpsertBulk) ClearUpdateTime() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *AssetDocumentUpsertBulk) SetDeleteTime(v time.Time) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateDeleteTime() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *AssetDocumentUpsertBulk) ClearDeleteTime() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearDeleteTime()
	})
}

// SetEntityType sets the "entity_type" field.
func (u *AssetDocumentUpsertBulk) SetEntityType(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateEntityType() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateEntityType()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *AssetDocumentUpsertBulk) SetEntityID(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateEntityID() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateEntityID()
	})
}

// SetFileName sets the "file_name" field.
func (u *AssetDocumentUpsertBulk) SetFileName(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateFileName() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateFileName()
	})
}

// SetFileSize sets the "file_size" field.
func (u *AssetDocumentUpsertBulk) SetFileSize(v int64) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *AssetDocumentUpsertBulk) AddFileSize(v int64) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateFileSize() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateFileSize()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *AssetDocumentUpsertBulk) SetMimeType(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateMimeType() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AssetDocumentUpsertBulk) ClearMimeType() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearMimeType()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *AssetDocumentUpsertBulk) SetStorageKey(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateStorageKey() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetChecksum sets the "checksum" field.
func (u *AssetDocumentUpsertBulk) SetChecksum(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateChecksum() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateChecksum()
	})
}

// ClearChecksum clears the value of the "checksum" field.
func (u *AssetDocumentUpsertBulk) ClearChecksum() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearChecksum()
	})
}

// SetDescription sets the "description" field.
func (u *AssetDocumentUpsertBulk) SetDescription(v string) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateDescription() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AssetDocumentUpsertBulk) ClearDescription() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearDescription()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *AssetDocumentUpsertBulk) SetUploadedBy(v uint32) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.SetUploadedBy(v)
	})
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *AssetDocumentUpsertBulk) AddUploadedBy(v uint32) *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.AddUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *AssetDocumentUpsertBulk) UpdateUploadedBy() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.UpdateUploadedBy()
	})
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *AssetDocumentUpsertBulk) ClearUploadedBy() *AssetDocumentUpsertBulk {
	return u.Update(func(s *AssetDocumentUpsert) {
		s.ClearUploadedBy()
	})
}

// Exec executes the query.
func (u *AssetDocumentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AssetDocumentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetDocumentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetDocumentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
