// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/insurancepolicyasset"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/predicate"
)

// InsurancePolicyAssetUpdate is the builder for updating InsurancePolicyAsset entities.
type InsurancePolicyAssetUpdate struct {
	config
	hooks     []Hook
	mutation  *InsurancePolicyAssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InsurancePolicyAssetUpdate builder.
func (_u *InsurancePolicyAssetUpdate) Where(ps ...predicate.InsurancePolicyAsset) *InsurancePolicyAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *InsurancePolicyAssetUpdate) SetCreateBy(v uint32) *InsurancePolicyAssetUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableCreateBy(v *uint32) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *InsurancePolicyAssetUpdate) AddCreateBy(v int32) *InsurancePolicyAssetUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *InsurancePolicyAssetUpdate) ClearCreateBy() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *InsurancePolicyAssetUpdate) SetUpdateTime(v time.Time) *InsurancePolicyAssetUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableUpdateTime(v *time.Time) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *InsurancePolicyAssetUpdate) ClearUpdateTime() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *InsurancePolicyAssetUpdate) SetDeleteTime(v time.Time) *InsurancePolicyAssetUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableDeleteTime(v *time.Time) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *InsurancePolicyAssetUpdate) ClearDeleteTime() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *InsurancePolicyAssetUpdate) SetPolicyID(v string) *InsurancePolicyAssetUpdate {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillablePolicyID(v *string) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *InsurancePolicyAssetUpdate) SetAssetID(v string) *InsurancePolicyAssetUpdate {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableAssetID(v *string) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InsurancePolicyAssetUpdate) SetTenantID(v uint32) *InsurancePolicyAssetUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableTenantID(v *uint32) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *InsurancePolicyAssetUpdate) AddTenantID(v int32) *InsurancePolicyAssetUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetCoveredValue sets the "covered_value" field.
func (_u *InsurancePolicyAssetUpdate) SetCoveredValue(v float64) *InsurancePolicyAssetUpdate {
	_u.mutation.ResetCoveredValue()
	_u.mutation.SetCoveredValue(v)
	return _u
}

// SetNillableCoveredValue sets the "covered_value" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableCoveredValue(v *float64) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetCoveredValue(*v)
	}
	return _u
}

// AddCoveredValue adds value to the "covered_value" field.
func (_u *InsurancePolicyAssetUpdate) AddCoveredValue(v float64) *InsurancePolicyAssetUpdate {
	_u.mutation.AddCoveredValue(v)
	return _u
}

// ClearCoveredValue clears the value of the "covered_value" field.
func (_u *InsurancePolicyAssetUpdate) ClearCoveredValue() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearCoveredValue()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InsurancePolicyAssetUpdate) SetNotes(v string) *InsurancePolicyAssetUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableNotes(v *string) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *InsurancePolicyAssetUpdate) ClearNotes() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetAssetTag sets the "asset_tag" field.
func (_u *InsurancePolicyAssetUpdate) SetAssetTag(v string) *InsurancePolicyAssetUpdate {
	_u.mutation.SetAssetTag(v)
	return _u
}

// SetNillableAssetTag sets the "asset_tag" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableAssetTag(v *string) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetAssetTag(*v)
	}
	return _u
}

// ClearAssetTag clears the value of the "asset_tag" field.
func (_u *InsurancePolicyAssetUpdate) ClearAssetTag() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearAssetTag()
	return _u
}

// SetAssetName sets the "asset_name" field.
func (_u *InsurancePolicyAssetUpdate) SetAssetName(v string) *InsurancePolicyAssetUpdate {
	_u.mutation.SetAssetName(v)
	return _u
}

// SetNillableAssetName sets the "asset_name" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableAssetName(v *string) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetAssetName(*v)
	}
	return _u
}

// ClearAssetName clears the value of the "asset_name" field.
func (_u *InsurancePolicyAssetUpdate) ClearAssetName() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearAssetName()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *InsurancePolicyAssetUpdate) SetModelName(v string) *InsurancePolicyAssetUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdate) SetNillableModelName(v *string) *InsurancePolicyAssetUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *InsurancePolicyAssetUpdate) ClearModelName() *InsurancePolicyAssetUpdate {
	_u.mutation.ClearModelName()
	return _u
}

// Mutation returns the InsurancePolicyAssetMutation object of the builder.
func (_u *InsurancePolicyAssetUpdate) Mutation() *InsurancePolicyAssetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InsurancePolicyAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InsurancePolicyAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InsurancePolicyAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InsurancePolicyAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InsurancePolicyAssetUpdate) check() error {
	if v, ok := _u.mutation.PolicyID(); ok {
		if err := insurancepolicyasset.PolicyIDValidator(v); err != nil {
			return &ValidationError{Name: "policy_id", err: fmt.Errorf(`ent: validator failed for field "InsurancePolicyAsset.policy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetID(); ok {
		if err := insurancepolicyasset.AssetIDValidator(v); err != nil {
			return &ValidationError{Name: "asset_id", err: fmt.Errorf(`ent: validator failed for field "InsurancePolicyAsset.asset_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InsurancePolicyAssetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InsurancePolicyAssetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InsurancePolicyAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(insurancepolicyasset.Table, insurancepolicyasset.Columns, sqlgraph.NewFieldSpec(insurancepolicyasset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(insurancepolicyasset.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(insurancepolicyasset.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(insurancepolicyasset.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(insurancepolicyasset.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(insurancepolicyasset.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(insurancepolicyasset.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(insurancepolicyasset.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(insurancepolicyasset.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.PolicyID(); ok {
		_spec.SetField(insurancepolicyasset.FieldPolicyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetID(); ok {
		_spec.SetField(insurancepolicyasset.FieldAssetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(insurancepolicyasset.FieldTenantID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(insurancepolicyasset.FieldTenantID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.CoveredValue(); ok {
		_spec.SetField(insurancepolicyasset.FieldCoveredValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCoveredValue(); ok {
		_spec.AddField(insurancepolicyasset.FieldCoveredValue, field.TypeFloat64, value)
	}
	if _u.mutation.CoveredValueCleared() {
		_spec.ClearField(insurancepolicyasset.FieldCoveredValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(insurancepolicyasset.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(insurancepolicyasset.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.AssetTag(); ok {
		_spec.SetField(insurancepolicyasset.FieldAssetTag, field.TypeString, value)
	}
	if _u.mutation.AssetTagCleared() {
		_spec.ClearField(insurancepolicyasset.FieldAssetTag, field.TypeString)
	}
	if value, ok := _u.mutation.AssetName(); ok {
		_spec.SetField(insurancepolicyasset.FieldAssetName, field.TypeString, value)
	}
	if _u.mutation.AssetNameCleared() {
		_spec.ClearField(insurancepolicyasset.FieldAssetName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(insurancepolicyasset.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(insurancepolicyasset.FieldModelName, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{insurancepolicyasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InsurancePolicyAssetUpdateOne is the builder for updating a single InsurancePolicyAsset entity.
type InsurancePolicyAssetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InsurancePolicyAssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *InsurancePolicyAssetUpdateOne) SetCreateBy(v uint32) *InsurancePolicyAssetUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableCreateBy(v *uint32) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *InsurancePolicyAssetUpdateOne) AddCreateBy(v int32) *InsurancePolicyAssetUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearCreateBy() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *InsurancePolicyAssetUpdateOne) SetUpdateTime(v time.Time) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableUpdateTime(v *time.Time) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearUpdateTime() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *InsurancePolicyAssetUpdateOne) SetDeleteTime(v time.Time) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableDeleteTime(v *time.Time) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearDeleteTime() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *InsurancePolicyAssetUpdateOne) SetPolicyID(v string) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillablePolicyID(v *string) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *InsurancePolicyAssetUpdateOne) SetAssetID(v string) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableAssetID(v *string) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InsurancePolicyAssetUpdateOne) SetTenantID(v uint32) *InsurancePolicyAssetUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableTenantID(v *uint32) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *InsurancePolicyAssetUpdateOne) AddTenantID(v int32) *InsurancePolicyAssetUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetCoveredValue sets the "covered_value" field.
func (_u *InsurancePolicyAssetUpdateOne) SetCoveredValue(v float64) *InsurancePolicyAssetUpdateOne {
	_u.mutation.ResetCoveredValue()
	_u.mutation.SetCoveredValue(v)
	return _u
}

// SetNillableCoveredValue sets the "covered_value" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableCoveredValue(v *float64) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetCoveredValue(*v)
	}
	return _u
}

// AddCoveredValue adds value to the "covered_value" field.
func (_u *InsurancePolicyAssetUpdateOne) AddCoveredValue(v float64) *InsurancePolicyAssetUpdateOne {
	_u.mutation.AddCoveredValue(v)
	return _u
}

// ClearCoveredValue clears the value of the "covered_value" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearCoveredValue() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearCoveredValue()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InsurancePolicyAssetUpdateOne) SetNotes(v string) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableNotes(v *string) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearNotes() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetAssetTag sets the "asset_tag" field.
func (_u *InsurancePolicyAssetUpdateOne) SetAssetTag(v string) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetAssetTag(v)
	return _u
}

// SetNillableAssetTag sets the "asset_tag" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableAssetTag(v *string) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetAssetTag(*v)
	}
	return _u
}

// ClearAssetTag clears the value of the "asset_tag" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearAssetTag() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearAssetTag()
	return _u
}

// SetAssetName sets the "asset_name" field.
func (_u *InsurancePolicyAssetUpdateOne) SetAssetName(v string) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetAssetName(v)
	return _u
}

// SetNillableAssetName sets the "asset_name" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableAssetName(v *string) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetAssetName(*v)
	}
	return _u
}

// ClearAssetName clears the value of the "asset_name" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearAssetName() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearAssetName()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *InsurancePolicyAssetUpdateOne) SetModelName(v string) *InsurancePolicyAssetUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *InsurancePolicyAssetUpdateOne) SetNillableModelName(v *string) *InsurancePolicyAssetUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *InsurancePolicyAssetUpdateOne) ClearModelName() *InsurancePolicyAssetUpdateOne {
	_u.mutation.ClearModelName()
	return _u
}

// Mutation returns the InsurancePolicyAssetMutation object of the builder.
func (_u *InsurancePolicyAssetUpdateOne) Mutation() *InsurancePolicyAssetMutation {
	return _u.mutation
}

// Where appends a list predicates to the InsurancePolicyAssetUpdate builder.
func (_u *InsurancePolicyAssetUpdateOne) Where(ps ...predicate.InsurancePolicyAsset) *InsurancePolicyAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InsurancePolicyAssetUpdateOne) Select(field string, fields ...string) *InsurancePolicyAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InsurancePolicyAsset entity.
func (_u *InsurancePolicyAssetUpdateOne) Save(ctx context.Context) (*InsurancePolicyAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InsurancePolicyAssetUpdateOne) SaveX(ctx context.Context) *InsurancePolicyAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InsurancePolicyAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InsurancePolicyAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InsurancePolicyAssetUpdateOne) check() error {
	if v, ok := _u.mutation.PolicyID(); ok {
		if err := insurancepolicyasset.PolicyIDValidator(v); err != nil {
			return &ValidationError{Name: "policy_id", err: fmt.Errorf(`ent: validator failed for field "InsurancePolicyAsset.policy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetID(); ok {
		if err := insurancepolicyasset.AssetIDValidator(v); err != nil {
			return &ValidationError{Name: "asset_id", err: fmt.Errorf(`ent: validator failed for field "InsurancePolicyAsset.asset_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InsurancePolicyAssetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InsurancePolicyAssetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InsurancePolicyAssetUpdateOne) sqlSave(ctx context.Context) (_node *InsurancePolicyAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(insurancepolicyasset.Table, insurancepolicyasset.Columns, sqlgraph.NewFieldSpec(insurancepolicyasset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InsurancePolicyAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, insurancepolicyasset.FieldID)
		for _, f := range fields {
			if !insurancepolicyasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != insurancepolicyasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(insurancepolicyasset.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(insurancepolicyasset.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(insurancepolicyasset.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(insurancepolicyasset.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(insurancepolicyasset.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(insurancepolicyasset.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(insurancepolicyasset.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(insurancepolicyasset.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.PolicyID(); ok {
		_spec.SetField(insurancepolicyasset.FieldPolicyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetID(); ok {
		_spec.SetField(insurancepolicyasset.FieldAssetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(insurancepolicyasset.FieldTenantID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(insurancepolicyasset.FieldTenantID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.CoveredValue(); ok {
		_spec.SetField(insurancepolicyasset.FieldCoveredValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCoveredValue(); ok {
		_spec.AddField(insurancepolicyasset.FieldCoveredValue, field.TypeFloat64, value)
	}
	if _u.mutation.CoveredValueCleared() {
		_spec.ClearField(insurancepolicyasset.FieldCoveredValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(insurancepolicyasset.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(insurancepolicyasset.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.AssetTag(); ok {
		_spec.SetField(insurancepolicyasset.FieldAssetTag, field.TypeString, value)
	}
	if _u.mutation.AssetTagCleared() {
		_spec.ClearField(insurancepolicyasset.FieldAssetTag, field.TypeString)
	}
	if value, ok := _u.mutation.AssetName(); ok {
		_spec.SetField(insurancepolicyasset.FieldAssetName, field.TypeString, value)
	}
	if _u.mutation.AssetNameCleared() {
		_spec.ClearField(insurancepolicyasset.FieldAssetName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(insurancepolicyasset.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(insurancepolicyasset.FieldModelName, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &InsurancePolicyAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{insurancepolicyasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
