// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/insurancepolicy"
)

// InsurancePolicyCreate is the builder for creating a InsurancePolicy entity.
type InsurancePolicyCreate struct {
	config
	mutation *InsurancePolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *InsurancePolicyCreate) SetCreateBy(v uint32) *InsurancePolicyCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableCreateBy(v *uint32) *InsurancePolicyCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *InsurancePolicyCreate) SetUpdateBy(v uint32) *InsurancePolicyCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableUpdateBy(v *uint32) *InsurancePolicyCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *InsurancePolicyCreate) SetCreateTime(v time.Time) *InsurancePolicyCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableCreateTime(v *time.Time) *InsurancePolicyCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *InsurancePolicyCreate) SetUpdateTime(v time.Time) *InsurancePolicyCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableUpdateTime(v *time.Time) *InsurancePolicyCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *InsurancePolicyCreate) SetDeleteTime(v time.Time) *InsurancePolicyCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableDeleteTime(v *time.Time) *InsurancePolicyCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *InsurancePolicyCreate) SetTenantID(v uint32) *InsurancePolicyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableTenantID(v *uint32) *InsurancePolicyCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *InsurancePolicyCreate) SetName(v string) *InsurancePolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPolicyNumber sets the "policy_number" field.
func (_c *InsurancePolicyCreate) SetPolicyNumber(v string) *InsurancePolicyCreate {
	_c.mutation.SetPolicyNumber(v)
	return _c
}

// SetNillablePolicyNumber sets the "policy_number" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillablePolicyNumber(v *string) *InsurancePolicyCreate {
	if v != nil {
		_c.SetPolicyNumber(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *InsurancePolicyCreate) SetProvider(v string) *InsurancePolicyCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableProvider(v *string) *InsurancePolicyCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetCoverageType sets the "coverage_type" field.
func (_c *InsurancePolicyCreate) SetCoverageType(v string) *InsurancePolicyCreate {
	_c.mutation.SetCoverageType(v)
	return _c
}

// SetNillableCoverageType sets the "coverage_type" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableCoverageType(v *string) *InsurancePolicyCreate {
	if v != nil {
		_c.SetCoverageType(*v)
	}
	return _c
}

// SetPremiumAmount sets the "premium_amount" field.
func (_c *InsurancePolicyCreate) SetPremiumAmount(v float64) *InsurancePolicyCreate {
	_c.mutation.SetPremiumAmount(v)
	return _c
}

// SetNillablePremiumAmount sets the "premium_amount" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillablePremiumAmount(v *float64) *InsurancePolicyCreate {
	if v != nil {
		_c.SetPremiumAmount(*v)
	}
	return _c
}

// SetDeductible sets the "deductible" field.
func (_c *InsurancePolicyCreate) SetDeductible(v float64) *InsurancePolicyCreate {
	_c.mutation.SetDeductible(v)
	return _c
}

// SetNillableDeductible sets the "deductible" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableDeductible(v *float64) *InsurancePolicyCreate {
	if v != nil {
		_c.SetDeductible(*v)
	}
	return _c
}

// SetCoverageLimit sets the "coverage_limit" field.
func (_c *InsurancePolicyCreate) SetCoverageLimit(v float64) *InsurancePolicyCreate {
	_c.mutation.SetCoverageLimit(v)
	return _c
}

// SetNillableCoverageLimit sets the "coverage_limit" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableCoverageLimit(v *float64) *InsurancePolicyCreate {
	if v != nil {
		_c.SetCoverageLimit(*v)
	}
	return _c
}

// SetValidFrom sets the "valid_from" field.
func (_c *InsurancePolicyCreate) SetValidFrom(v time.Time) *InsurancePolicyCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableValidFrom(v *time.Time) *InsurancePolicyCreate {
	if v != nil {
		_c.SetValidFrom(*v)
	}
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *InsurancePolicyCreate) SetValidTo(v time.Time) *InsurancePolicyCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableValidTo(v *time.Time) *InsurancePolicyCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InsurancePolicyCreate) SetStatus(v string) *InsurancePolicyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableStatus(v *string) *InsurancePolicyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *InsurancePolicyCreate) SetNotes(v string) *InsurancePolicyCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *InsurancePolicyCreate) SetNillableNotes(v *string) *InsurancePolicyCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InsurancePolicyCreate) SetID(v string) *InsurancePolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InsurancePolicyMutation object of the builder.
func (_c *InsurancePolicyCreate) Mutation() *InsurancePolicyMutation {
	return _c.mutation
}

// Save creates the InsurancePolicy in the database.
func (_c *InsurancePolicyCreate) Save(ctx context.Context) (*InsurancePolicy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InsurancePolicyCreate) SaveX(ctx context.Context) *InsurancePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InsurancePolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InsurancePolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InsurancePolicyCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := insurancepolicy.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := insurancepolicy.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *InsurancePolicyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "InsurancePolicy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := insurancepolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InsurancePolicy.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := insurancepolicy.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "InsurancePolicy.id": %w`, err)}
		}
	}
	return nil
}

func (_c *InsurancePolicyCreate) sqlSave(ctx context.Context) (*InsurancePolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected InsurancePolicy.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InsurancePolicyCreate) createSpec() (*InsurancePolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &InsurancePolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(insurancepolicy.Table, sqlgraph.NewFieldSpec(insurancepolicy.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(insurancepolicy.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(insurancepolicy.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(insurancepolicy.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(insurancepolicy.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(insurancepolicy.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(insurancepolicy.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(insurancepolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PolicyNumber(); ok {
		_spec.SetField(insurancepolicy.FieldPolicyNumber, field.TypeString, value)
		_node.PolicyNumber = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(insurancepolicy.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.CoverageType(); ok {
		_spec.SetField(insurancepolicy.FieldCoverageType, field.TypeString, value)
		_node.CoverageType = value
	}
	if value, ok := _c.mutation.PremiumAmount(); ok {
		_spec.SetField(insurancepolicy.FieldPremiumAmount, field.TypeFloat64, value)
		_node.PremiumAmount = &value
	}
	if value, ok := _c.mutation.Deductible(); ok {
		_spec.SetField(insurancepolicy.FieldDeductible, field.TypeFloat64, value)
		_node.Deductible = &value
	}
	if value, ok := _c.mutation.CoverageLimit(); ok {
		_spec.SetField(insurancepolicy.FieldCoverageLimit, field.TypeFloat64, value)
		_node.CoverageLimit = &value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(insurancepolicy.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = &value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(insurancepolicy.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(insurancepolicy.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(insurancepolicy.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InsurancePolicy.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InsurancePolicyUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *InsurancePolicyCreate) OnConflict(opts ...sql.ConflictOption) *InsurancePolicyUpsertOne {
	_c.conflict = opts
	return &InsurancePolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InsurancePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InsurancePolicyCreate) OnConflictColumns(columns ...string) *InsurancePolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InsurancePolicyUpsertOne{
		create: _c,
	}
}

type (
	// InsurancePolicyUpsertOne is the builder for "upsert"-ing
	//  one InsurancePolicy node.
	InsurancePolicyUpsertOne struct {
		create *InsurancePolicyCreate
	}

	// InsurancePolicyUpsert is the "OnConflict" setter.
	InsurancePolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *InsurancePolicyUpsert) SetCreateBy(v uint32) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateCreateBy() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *InsurancePolicyUpsert) AddCreateBy(v uint32) *InsurancePolicyUpsert {
	u.Add(insurancepolicy.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *InsurancePolicyUpsert) ClearCreateBy() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *InsurancePolicyUpsert) SetUpdateBy(v uint32) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateUpdateBy() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *InsurancePolicyUpsert) AddUpdateBy(v uint32) *InsurancePolicyUpsert {
	u.Add(insurancepolicy.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *InsurancePolicyUpsert) ClearUpdateBy() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *InsurancePolicyUpsert) SetUpdateTime(v time.Time) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateUpdateTime() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *InsurancePolicyUpsert) ClearUpdateTime() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *InsurancePolicyUpsert) SetDeleteTime(v time.Time) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateDeleteTime() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *InsurancePolicyUpsert) ClearDeleteTime() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *InsurancePolicyUpsert) SetName(v string) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateName() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldName)
	return u
}

// SetPolicyNumber sets the "policy_number" field.
func (u *InsurancePolicyUpsert) SetPolicyNumber(v string) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldPolicyNumber, v)
	return u
}

// UpdatePolicyNumber sets the "policy_number" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdatePolicyNumber() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldPolicyNumber)
	return u
}

// ClearPolicyNumber clears the value of the "policy_number" field.
func (u *InsurancePolicyUpsert) ClearPolicyNumber() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldPolicyNumber)
	return u
}

// SetProvider sets the "provider" field.
func (u *InsurancePolicyUpsert) SetProvider(v string) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateProvider() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *InsurancePolicyUpsert) ClearProvider() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldProvider)
	return u
}

// SetCoverageType sets the "coverage_type" field.
func (u *InsurancePolicyUpsert) SetCoverageType(v string) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldCoverageType, v)
	return u
}

// UpdateCoverageType sets the "coverage_type" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateCoverageType() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldCoverageType)
	return u
}

// ClearCoverageType clears the value of the "coverage_type" field.
func (u *InsurancePolicyUpsert) ClearCoverageType() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldCoverageType)
	return u
}

// SetPremiumAmount sets the "premium_amount" field.
func (u *InsurancePolicyUpsert) SetPremiumAmount(v float64) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldPremiumAmount, v)
	return u
}

// UpdatePremiumAmount sets the "premium_amount" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdatePremiumAmount() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldPremiumAmount)
	return u
}

// AddPremiumAmount adds v to the "premium_amount" field.
func (u *InsurancePolicyUpsert) AddPremiumAmount(v float64) *InsurancePolicyUpsert {
	u.Add(insurancepolicy.FieldPremiumAmount, v)
	return u
}

// ClearPremiumAmount clears the value of the "premium_amount" field.
func (u *InsurancePolicyUpsert) ClearPremiumAmount() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldPremiumAmount)
	return u
}

// SetDeductible sets the "deductible" field.
func (u *InsurancePolicyUpsert) SetDeductible(v float64) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldDeductible, v)
	return u
}

// UpdateDeductible sets the "deductible" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateDeductible() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldDeductible)
	return u
}

// AddDeductible adds v to the "deductible" field.
func (u *InsurancePolicyUpsert) AddDeductible(v float64) *InsurancePolicyUpsert {
	u.Add(insurancepolicy.FieldDeductible, v)
	return u
}

// ClearDeductible clears the value of the "deductible" field.
func (u *InsurancePolicyUpsert) ClearDeductible() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldDeductible)
	return u
}

// SetCoverageLimit sets the "coverage_limit" field.
func (u *InsurancePolicyUpsert) SetCoverageLimit(v float64) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldCoverageLimit, v)
	return u
}

// UpdateCoverageLimit sets the "coverage_limit" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateCoverageLimit() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldCoverageLimit)
	return u
}

// AddCoverageLimit adds v to the "coverage_limit" field.
func (u *InsurancePolicyUpsert) AddCoverageLimit(v float64) *InsurancePolicyUpsert {
	u.Add(insurancepolicy.FieldCoverageLimit, v)
	return u
}

// ClearCoverageLimit clears the value of the "coverage_limit" field.
func (u *InsurancePolicyUpsert) ClearCoverageLimit() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldCoverageLimit)
	return u
}

// SetValidFrom sets the "valid_from" field.
func (u *InsurancePolicyUpsert) SetValidFrom(v time.Time) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldValidFrom, v)
	return u
}

// UpdateValidFrom sets the "valid_from" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateValidFrom() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldValidFrom)
	return u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (u *InsurancePolicyUpsert) ClearValidFrom() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldValidFrom)
	return u
}

// SetValidTo sets the "valid_to" field.
func (u *InsurancePolicyUpsert) SetValidTo(v time.Time) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldValidTo, v)
	return u
}

// UpdateValidTo sets the "valid_to" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateValidTo() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldValidTo)
	return u
}

// ClearValidTo clears the value of the "valid_to" field.
func (u *InsurancePolicyUpsert) ClearValidTo() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldValidTo)
	return u
}

// SetStatus sets the "status" field.
func (u *InsurancePolicyUpsert) SetStatus(v string) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateStatus() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *InsurancePolicyUpsert) ClearStatus() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *InsurancePolicyUpsert) SetNotes(v string) *InsurancePolicyUpsert {
	u.Set(insurancepolicy.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *InsurancePolicyUpsert) UpdateNotes() *InsurancePolicyUpsert {
	u.SetExcluded(insurancepolicy.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *InsurancePolicyUpsert) ClearNotes() *InsurancePolicyUpsert {
	u.SetNull(insurancepolicy.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.InsurancePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(insurancepolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InsurancePolicyUpsertOne) UpdateNewValues() *InsurancePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(insurancepolicy.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(insurancepolicy.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(insurancepolicy.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InsurancePolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InsurancePolicyUpsertOne) Ignore() *InsurancePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InsurancePolicyUpsertOne) DoNothing() *InsurancePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InsurancePolicyCreate.OnConflict
// documentation for more info.
func (u *InsurancePolicyUpsertOne) Update(set func(*InsurancePolicyUpsert)) *InsurancePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InsurancePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *InsurancePolicyUpsertOne) SetCreateBy(v uint32) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *InsurancePolicyUpsertOne) AddCreateBy(v uint32) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateCreateBy() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *InsurancePolicyUpsertOne) ClearCreateBy() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *InsurancePolicyUpsertOne) SetUpdateBy(v uint32) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *InsurancePolicyUpsertOne) AddUpdateBy(v uint32) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateUpdateBy() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *InsurancePolicyUpsertOne) ClearUpdateBy() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *InsurancePolicyUpsertOne) SetUpdateTime(v time.Time) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateUpdateTime() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *InsurancePolicyUpsertOne) ClearUpdateTime() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *InsurancePolicyUpsertOne) SetDeleteTime(v time.Time) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateDeleteTime() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *InsurancePolicyUpsertOne) ClearDeleteTime() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *InsurancePolicyUpsertOne) SetName(v string) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateName() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateName()
	})
}

// SetPolicyNumber sets the "policy_number" field.
func (u *InsurancePolicyUpsertOne) SetPolicyNumber(v string) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetPolicyNumber(v)
	})
}

// UpdatePolicyNumber sets the "policy_number" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdatePolicyNumber() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdatePolicyNumber()
	})
}

// ClearPolicyNumber clears the value of the "policy_number" field.
func (u *InsurancePolicyUpsertOne) ClearPolicyNumber() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearPolicyNumber()
	})
}

// SetProvider sets the "provider" field.
func (u *InsurancePolicyUpsertOne) SetProvider(v string) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateProvider() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *InsurancePolicyUpsertOne) ClearProvider() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearProvider()
	})
}

// SetCoverageType sets the "coverage_type" field.
func (u *InsurancePolicyUpsertOne) SetCoverageType(v string) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetCoverageType(v)
	})
}

// UpdateCoverageType sets the "coverage_type" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateCoverageType() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateCoverageType()
	})
}

// ClearCoverageType clears the value of the "coverage_type" field.
func (u *InsurancePolicyUpsertOne) ClearCoverageType() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearCoverageType()
	})
}

// SetPremiumAmount sets the "premium_amount" field.
func (u *InsurancePolicyUpsertOne) SetPremiumAmount(v float64) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetPremiumAmount(v)
	})
}

// AddPremiumAmount adds v to the "premium_amount" field.
func (u *InsurancePolicyUpsertOne) AddPremiumAmount(v float64) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddPremiumAmount(v)
	})
}

// UpdatePremiumAmount sets the "premium_amount" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdatePremiumAmount() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdatePremiumAmount()
	})
}

// ClearPremiumAmount clears the value of the "premium_amount" field.
func (u *InsurancePolicyUpsertOne) ClearPremiumAmount() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearPremiumAmount()
	})
}

// SetDeductible sets the "deductible" field.
func (u *InsurancePolicyUpsertOne) SetDeductible(v float64) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetDeductible(v)
	})
}

// AddDeductible adds v to the "deductible" field.
func (u *InsurancePolicyUpsertOne) AddDeductible(v float64) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddDeductible(v)
	})
}

// UpdateDeductible sets the "deductible" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateDeductible() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateDeductible()
	})
}

// ClearDeductible clears the value of the "deductible" field.
func (u *InsurancePolicyUpsertOne) ClearDeductible() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearDeductible()
	})
}

// SetCoverageLimit sets the "coverage_limit" field.
func (u *InsurancePolicyUpsertOne) SetCoverageLimit(v float64) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetCoverageLimit(v)
	})
}

// AddCoverageLimit adds v to the "coverage_limit" field.
func (u *InsurancePolicyUpsertOne) AddCoverageLimit(v float64) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddCoverageLimit(v)
	})
}

// UpdateCoverageLimit sets the "coverage_limit" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateCoverageLimit() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateCoverageLimit()
	})
}

// ClearCoverageLimit clears the value of the "coverage_limit" field.
func (u *InsurancePolicyUpsertOne) ClearCoverageLimit() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearCoverageLimit()
	})
}

// SetValidFrom sets the "valid_from" field.
func (u *InsurancePolicyUpsertOne) SetValidFrom(v time.Time) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetValidFrom(v)
	})
}

// UpdateValidFrom sets the "valid_from" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateValidFrom() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateValidFrom()
	})
}

// ClearValidFrom clears the value of the "valid_from" field.
func (u *InsurancePolicyUpsertOne) ClearValidFrom() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearValidFrom()
	})
}

// SetValidTo sets the "valid_to" field.
func (u *InsurancePolicyUpsertOne) SetValidTo(v time.Time) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetValidTo(v)
	})
}

// UpdateValidTo sets the "valid_to" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateValidTo() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateValidTo()
	})
}

// ClearValidTo clears the value of the "valid_to" field.
func (u *InsurancePolicyUpsertOne) ClearValidTo() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearValidTo()
	})
}

// SetStatus sets the "status" field.
func (u *InsurancePolicyUpsertOne) SetStatus(v string) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateStatus() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *InsurancePolicyUpsertOne) ClearStatus() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *InsurancePolicyUpsertOne) SetNotes(v string) *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *InsurancePolicyUpsertOne) UpdateNotes() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *InsurancePolicyUpsertOne) ClearNotes() *InsurancePolicyUpsertOne {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *InsurancePolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InsurancePolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InsurancePolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InsurancePolicyUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InsurancePolicyUpsertOne.ID is not supported by MySQL driver. Use InsurancePolicyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InsurancePolicyUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InsurancePolicyCreateBulk is the builder for creating many InsurancePolicy entities in bulk.
type InsurancePolicyCreateBulk struct {
	config
	err      error
	builders []*InsurancePolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the InsurancePolicy entities in the database.
func (_c *InsurancePolicyCreateBulk) Save(ctx context.Context) ([]*InsurancePolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InsurancePolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InsurancePolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InsurancePolicyCreateBulk) SaveX(ctx context.Context) []*InsurancePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InsurancePolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InsurancePolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InsurancePolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InsurancePolicyUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *InsurancePolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *InsurancePolicyUpsertBulk {
	_c.conflict = opts
	return &InsurancePolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InsurancePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InsurancePolicyCreateBulk) OnConflictColumns(columns ...string) *InsurancePolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InsurancePolicyUpsertBulk{
		create: _c,
	}
}

// InsurancePolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of InsurancePolicy nodes.
type InsurancePolicyUpsertBulk struct {
	create *InsurancePolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InsurancePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(insurancepolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InsurancePolicyUpsertBulk) UpdateNewValues() *InsurancePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(insurancepolicy.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(insurancepolicy.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(insurancepolicy.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InsurancePolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InsurancePolicyUpsertBulk) Ignore() *InsurancePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InsurancePolicyUpsertBulk) DoNothing() *InsurancePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InsurancePolicyCreateBulk.OnConflict
// documentation for more info.
func (u *InsurancePolicyUpsertBulk) Update(set func(*InsurancePolicyUpsert)) *InsurancePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InsurancePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *InsurancePolicyUpsertBulk) SetCreateBy(v uint32) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *InsurancePolicyUpsertBulk) AddCreateBy(v uint32) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateCreateBy() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *InsurancePolicyUpsertBulk) ClearCreateBy() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *InsurancePolicyUpsertBulk) SetUpdateBy(v uint32) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *InsurancePolicyUpsertBulk) AddUpdateBy(v uint32) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateUpdateBy() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *InsurancePolicyUpsertBulk) ClearUpdateBy() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *InsurancePolicyUpsertBulk) SetUpdateTime(v time.Time) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateUpdateTime() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *InsurancePolicyUpsertBulk) ClearUpdateTime() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *InsurancePolicyUpsertBulk) SetDeleteTime(v time.Time) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateDeleteTime() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *InsurancePolicyUpsertBulk) ClearDeleteTime() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *InsurancePolicyUpsertBulk) SetName(v string) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateName() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateName()
	})
}

// SetPolicyNumber sets the "policy_number" field.
func (u *InsurancePolicyUpsertBulk) SetPolicyNumber(v string) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetPolicyNumber(v)
	})
}

// UpdatePolicyNumber sets the "policy_number" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdatePolicyNumber() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdatePolicyNumber()
	})
}

// ClearPolicyNumber clears the value of the "policy_number" field.
func (u *InsurancePolicyUpsertBulk) ClearPolicyNumber() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearPolicyNumber()
	})
}

// SetProvider sets the "provider" field.
func (u *InsurancePolicyUpsertBulk) SetProvider(v string) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateProvider() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *InsurancePolicyUpsertBulk) ClearProvider() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearProvider()
	})
}

// SetCoverageType sets the "coverage_type" field.
func (u *InsurancePolicyUpsertBulk) SetCoverageType(v string) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetCoverageType(v)
	})
}

// UpdateCoverageType sets the "coverage_type" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateCoverageType() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateCoverageType()
	})
}

// ClearCoverageType clears the value of the "coverage_type" field.
func (u *InsurancePolicyUpsertBulk) ClearCoverageType() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearCoverageType()
	})
}

// SetPremiumAmount sets the "premium_amount" field.
func (u *InsurancePolicyUpsertBulk) SetPremiumAmount(v float64) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetPremiumAmount(v)
	})
}

// AddPremiumAmount adds v to the "premium_amount" field.
func (u *InsurancePolicyUpsertBulk) AddPremiumAmount(v float64) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddPremiumAmount(v)
	})
}

// UpdatePremiumAmount sets the "premium_amount" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdatePremiumAmount() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdatePremiumAmount()
	})
}

// ClearPremiumAmount clears the value of the "premium_amount" field.
func (u *InsurancePolicyUpsertBulk) ClearPremiumAmount() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearPremiumAmount()
	})
}

// SetDeductible sets the "deductible" field.
func (u *InsurancePolicyUpsertBulk) SetDeductible(v float64) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetDeductible(v)
	})
}

// AddDeductible adds v to the "deductible" field.
func (u *InsurancePolicyUpsertBulk) AddDeductible(v float64) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddDeductible(v)
	})
}

// UpdateDeductible sets the "deductible" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateDeductible() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateDeductible()
	})
}

// ClearDeductible clears the value of the "deductible" field.
func (u *InsurancePolicyUpsertBulk) ClearDeductible() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearDeductible()
	})
}

// SetCoverageLimit sets the "coverage_limit" field.
func (u *InsurancePolicyUpsertBulk) SetCoverageLimit(v float64) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetCoverageLimit(v)
	})
}

// AddCoverageLimit adds v to the "coverage_limit" field.
func (u *InsurancePolicyUpsertBulk) AddCoverageLimit(v float64) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.AddCoverageLimit(v)
	})
}

// UpdateCoverageLimit sets the "coverage_limit" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateCoverageLimit() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateCoverageLimit()
	})
}

// ClearCoverageLimit clears the value of the "coverage_limit" field.
func (u *InsurancePolicyUpsertBulk) ClearCoverageLimit() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearCoverageLimit()
	})
}

// SetValidFrom sets the "valid_from" field.
func (u *InsurancePolicyUpsertBulk) SetValidFrom(v time.Time) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetValidFrom(v)
	})
}

// UpdateValidFrom sets the "valid_from" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateValidFrom() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateValidFrom()
	})
}

// ClearValidFrom clears the value of the "valid_from" field.
func (u *InsurancePolicyUpsertBulk) ClearValidFrom() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearValidFrom()
	})
}

// SetValidTo sets the "valid_to" field.
func (u *InsurancePolicyUpsertBulk) SetValidTo(v time.Time) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetValidTo(v)
	})
}

// UpdateValidTo sets the "valid_to" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateValidTo() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateValidTo()
	})
}

// ClearValidTo clears the value of the "valid_to" field.
func (u *InsurancePolicyUpsertBulk) ClearValidTo() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearValidTo()
	})
}

// SetStatus sets the "status" field.
func (u *InsurancePolicyUpsertBulk) SetStatus(v string) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateStatus() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *InsurancePolicyUpsertBulk) ClearStatus() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *InsurancePolicyUpsertBulk) SetNotes(v string) *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *InsurancePolicyUpsertBulk) UpdateNotes() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *InsurancePolicyUpsertBulk) ClearNotes() *InsurancePolicyUpsertBulk {
	return u.Update(func(s *InsurancePolicyUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *InsurancePolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InsurancePolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InsurancePolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InsurancePolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
