// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/license"
	"github.com/go-tangra/go-tangra-asset/internal/data/ent/supplier"
)

// LicenseCreate is the builder for creating a License entity.
type LicenseCreate struct {
	config
	mutation *LicenseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *LicenseCreate) SetCreateBy(v uint32) *LicenseCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableCreateBy(v *uint32) *LicenseCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *LicenseCreate) SetUpdateBy(v uint32) *LicenseCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableUpdateBy(v *uint32) *LicenseCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *LicenseCreate) SetCreateTime(v time.Time) *LicenseCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableCreateTime(v *time.Time) *LicenseCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *LicenseCreate) SetUpdateTime(v time.Time) *LicenseCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableUpdateTime(v *time.Time) *LicenseCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *LicenseCreate) SetDeleteTime(v time.Time) *LicenseCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableDeleteTime(v *time.Time) *LicenseCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *LicenseCreate) SetTenantID(v uint32) *LicenseCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableTenantID(v *uint32) *LicenseCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *LicenseCreate) SetName(v string) *LicenseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSupplierID sets the "supplier_id" field.
func (_c *LicenseCreate) SetSupplierID(v string) *LicenseCreate {
	_c.mutation.SetSupplierID(v)
	return _c
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableSupplierID(v *string) *LicenseCreate {
	if v != nil {
		_c.SetSupplierID(*v)
	}
	return _c
}

// SetPurchaseDate sets the "purchase_date" field.
func (_c *LicenseCreate) SetPurchaseDate(v time.Time) *LicenseCreate {
	_c.mutation.SetPurchaseDate(v)
	return _c
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_c *LicenseCreate) SetNillablePurchaseDate(v *time.Time) *LicenseCreate {
	if v != nil {
		_c.SetPurchaseDate(*v)
	}
	return _c
}

// SetPurchaseCost sets the "purchase_cost" field.
func (_c *LicenseCreate) SetPurchaseCost(v float64) *LicenseCreate {
	_c.mutation.SetPurchaseCost(v)
	return _c
}

// SetNillablePurchaseCost sets the "purchase_cost" field if the given value is not nil.
func (_c *LicenseCreate) SetNillablePurchaseCost(v *float64) *LicenseCreate {
	if v != nil {
		_c.SetPurchaseCost(*v)
	}
	return _c
}

// SetOrderNumber sets the "order_number" field.
func (_c *LicenseCreate) SetOrderNumber(v string) *LicenseCreate {
	_c.mutation.SetOrderNumber(v)
	return _c
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableOrderNumber(v *string) *LicenseCreate {
	if v != nil {
		_c.SetOrderNumber(*v)
	}
	return _c
}

// SetValidFrom sets the "valid_from" field.
func (_c *LicenseCreate) SetValidFrom(v time.Time) *LicenseCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableValidFrom(v *time.Time) *LicenseCreate {
	if v != nil {
		_c.SetValidFrom(*v)
	}
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *LicenseCreate) SetValidTo(v time.Time) *LicenseCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableValidTo(v *time.Time) *LicenseCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *LicenseCreate) SetNotes(v string) *LicenseCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableNotes(v *string) *LicenseCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *LicenseCreate) SetMetadata(v map[string]interface{}) *LicenseCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LicenseCreate) SetStatus(v string) *LicenseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LicenseCreate) SetNillableStatus(v *string) *LicenseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LicenseCreate) SetID(v string) *LicenseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_c *LicenseCreate) SetSupplier(v *Supplier) *LicenseCreate {
	return _c.SetSupplierID(v.ID)
}

// Mutation returns the LicenseMutation object of the builder.
func (_c *LicenseCreate) Mutation() *LicenseMutation {
	return _c.mutation
}

// Save creates the License in the database.
func (_c *LicenseCreate) Save(ctx context.Context) (*License, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LicenseCreate) SaveX(ctx context.Context) *License {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LicenseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LicenseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LicenseCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := license.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := license.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *LicenseCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "License.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := license.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "License.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := license.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "License.id": %w`, err)}
		}
	}
	return nil
}

func (_c *LicenseCreate) sqlSave(ctx context.Context) (*License, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected License.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LicenseCreate) createSpec() (*License, *sqlgraph.CreateSpec) {
	var (
		_node = &License{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(license.Table, sqlgraph.NewFieldSpec(license.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(license.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(license.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(license.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(license.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(license.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(license.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(license.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PurchaseDate(); ok {
		_spec.SetField(license.FieldPurchaseDate, field.TypeTime, value)
		_node.PurchaseDate = &value
	}
	if value, ok := _c.mutation.PurchaseCost(); ok {
		_spec.SetField(license.FieldPurchaseCost, field.TypeFloat64, value)
		_node.PurchaseCost = &value
	}
	if value, ok := _c.mutation.OrderNumber(); ok {
		_spec.SetField(license.FieldOrderNumber, field.TypeString, value)
		_node.OrderNumber = value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(license.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = &value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(license.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(license.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(license.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(license.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   license.SupplierTable,
			Columns: []string{license.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SupplierID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.License.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LicenseUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *LicenseCreate) OnConflict(opts ...sql.ConflictOption) *LicenseUpsertOne {
	_c.conflict = opts
	return &LicenseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.License.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LicenseCreate) OnConflictColumns(columns ...string) *LicenseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LicenseUpsertOne{
		create: _c,
	}
}

type (
	// LicenseUpsertOne is the builder for "upsert"-ing
	//  one License node.
	LicenseUpsertOne struct {
		create *LicenseCreate
	}

	// LicenseUpsert is the "OnConflict" setter.
	LicenseUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *LicenseUpsert) SetCreateBy(v uint32) *LicenseUpsert {
	u.Set(license.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateCreateBy() *LicenseUpsert {
	u.SetExcluded(license.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *LicenseUpsert) AddCreateBy(v uint32) *LicenseUpsert {
	u.Add(license.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *LicenseUpsert) ClearCreateBy() *LicenseUpsert {
	u.SetNull(license.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *LicenseUpsert) SetUpdateBy(v uint32) *LicenseUpsert {
	u.Set(license.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateUpdateBy() *LicenseUpsert {
	u.SetExcluded(license.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *LicenseUpsert) AddUpdateBy(v uint32) *LicenseUpsert {
	u.Add(license.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *LicenseUpsert) ClearUpdateBy() *LicenseUpsert {
	u.SetNull(license.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *LicenseUpsert) SetUpdateTime(v time.Time) *LicenseUpsert {
	u.Set(license.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateUpdateTime() *LicenseUpsert {
	u.SetExcluded(license.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *LicenseUpsert) ClearUpdateTime() *LicenseUpsert {
	u.SetNull(license.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *LicenseUpsert) SetDeleteTime(v time.Time) *LicenseUpsert {
	u.Set(license.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateDeleteTime() *LicenseUpsert {
	u.SetExcluded(license.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *LicenseUpsert) ClearDeleteTime() *LicenseUpsert {
	u.SetNull(license.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *LicenseUpsert) SetName(v string) *LicenseUpsert {
	u.Set(license.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateName() *LicenseUpsert {
	u.SetExcluded(license.FieldName)
	return u
}

// SetSupplierID sets the "supplier_id" field.
func (u *LicenseUpsert) SetSupplierID(v string) *LicenseUpsert {
	u.Set(license.FieldSupplierID, v)
	return u
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateSupplierID() *LicenseUpsert {
	u.SetExcluded(license.FieldSupplierID)
	return u
}

// ClearSupplierID clears the value of the "supplier_id" field.
func (u *LicenseUpsert) ClearSupplierID() *LicenseUpsert {
	u.SetNull(license.FieldSupplierID)
	return u
}

// SetPurchaseDate sets the "purchase_date" field.
func (u *LicenseUpsert) SetPurchaseDate(v time.Time) *LicenseUpsert {
	u.Set(license.FieldPurchaseDate, v)
	return u
}

// UpdatePurchaseDate sets the "purchase_date" field to the value that was provided on create.
func (u *LicenseUpsert) UpdatePurchaseDate() *LicenseUpsert {
	u.SetExcluded(license.FieldPurchaseDate)
	return u
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (u *LicenseUpsert) ClearPurchaseDate() *LicenseUpsert {
	u.SetNull(license.FieldPurchaseDate)
	return u
}

// SetPurchaseCost sets the "purchase_cost" field.
func (u *LicenseUpsert) SetPurchaseCost(v float64) *LicenseUpsert {
	u.Set(license.FieldPurchaseCost, v)
	return u
}

// UpdatePurchaseCost sets the "purchase_cost" field to the value that was provided on create.
func (u *LicenseUpsert) UpdatePurchaseCost() *LicenseUpsert {
	u.SetExcluded(license.FieldPurchaseCost)
	return u
}

// AddPurchaseCost adds v to the "purchase_cost" field.
func (u *LicenseUpsert) AddPurchaseCost(v float64) *LicenseUpsert {
	u.Add(license.FieldPurchaseCost, v)
	return u
}

// ClearPurchaseCost clears the value of the "purchase_cost" field.
func (u *LicenseUpsert) ClearPurchaseCost() *LicenseUpsert {
	u.SetNull(license.FieldPurchaseCost)
	return u
}

// SetOrderNumber sets the "order_number" field.
func (u *LicenseUpsert) SetOrderNumber(v string) *LicenseUpsert {
	u.Set(license.FieldOrderNumber, v)
	return u
}

// UpdateOrderNumber sets the "order_number" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateOrderNumber() *LicenseUpsert {
	u.SetExcluded(license.FieldOrderNumber)
	return u
}

// ClearOrderNumber clears the value of the "order_number" field.
func (u *LicenseUpsert) ClearOrderNumber() *LicenseUpsert {
	u.SetNull(license.FieldOrderNumber)
	return u
}

// SetValidFrom sets the "valid_from" field.
func (u *LicenseUpsert) SetValidFrom(v time.Time) *LicenseUpsert {
	u.Set(license.FieldValidFrom, v)
	return u
}

// UpdateValidFrom sets the "valid_from" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateValidFrom() *LicenseUpsert {
	u.SetExcluded(license.FieldValidFrom)
	return u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (u *LicenseUpsert) ClearValidFrom() *LicenseUpsert {
	u.SetNull(license.FieldValidFrom)
	return u
}

// SetValidTo sets the "valid_to" field.
func (u *LicenseUpsert) SetValidTo(v time.Time) *LicenseUpsert {
	u.Set(license.FieldValidTo, v)
	return u
}

// UpdateValidTo sets the "valid_to" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateValidTo() *LicenseUpsert {
	u.SetExcluded(license.FieldValidTo)
	return u
}

// ClearValidTo clears the value of the "valid_to" field.
func (u *LicenseUpsert) ClearValidTo() *LicenseUpsert {
	u.SetNull(license.FieldValidTo)
	return u
}

// SetNotes sets the "notes" field.
func (u *LicenseUpsert) SetNotes(v string) *LicenseUpsert {
	u.Set(license.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateNotes() *LicenseUpsert {
	u.SetExcluded(license.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *LicenseUpsert) ClearNotes() *LicenseUpsert {
	u.SetNull(license.FieldNotes)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *LicenseUpsert) SetMetadata(v map[string]interface{}) *LicenseUpsert {
	u.Set(license.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateMetadata() *LicenseUpsert {
	u.SetExcluded(license.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LicenseUpsert) ClearMetadata() *LicenseUpsert {
	u.SetNull(license.FieldMetadata)
	return u
}

// SetStatus sets the "status" field.
func (u *LicenseUpsert) SetStatus(v string) *LicenseUpsert {
	u.Set(license.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LicenseUpsert) UpdateStatus() *LicenseUpsert {
	u.SetExcluded(license.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *LicenseUpsert) ClearStatus() *LicenseUpsert {
	u.SetNull(license.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.License.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(license.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LicenseUpsertOne) UpdateNewValues() *LicenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(license.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(license.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(license.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.License.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LicenseUpsertOne) Ignore() *LicenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LicenseUpsertOne) DoNothing() *LicenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LicenseCreate.OnConflict
// documentation for more info.
func (u *LicenseUpsertOne) Update(set func(*LicenseUpsert)) *LicenseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LicenseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *LicenseUpsertOne) SetCreateBy(v uint32) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *LicenseUpsertOne) AddCreateBy(v uint32) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateCreateBy() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *LicenseUpsertOne) ClearCreateBy() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *LicenseUpsertOne) SetUpdateBy(v uint32) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *LicenseUpsertOne) AddUpdateBy(v uint32) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateUpdateBy() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *LicenseUpsertOne) ClearUpdateBy() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *LicenseUpsertOne) SetUpdateTime(v time.Time) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateUpdateTime() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *LicenseUpsertOne) ClearUpdateTime() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *LicenseUpsertOne) SetDeleteTime(v time.Time) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateDeleteTime() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *LicenseUpsertOne) ClearDeleteTime() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *LicenseUpsertOne) SetName(v string) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateName() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateName()
	})
}

// SetSupplierID sets the "supplier_id" field.
func (u *LicenseUpsertOne) SetSupplierID(v string) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetSupplierID(v)
	})
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateSupplierID() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateSupplierID()
	})
}

// ClearSupplierID clears the value of the "supplier_id" field.
func (u *LicenseUpsertOne) ClearSupplierID() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearSupplierID()
	})
}

// SetPurchaseDate sets the "purchase_date" field.
func (u *LicenseUpsertOne) SetPurchaseDate(v time.Time) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetPurchaseDate(v)
	})
}

// UpdatePurchaseDate sets the "purchase_date" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdatePurchaseDate() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdatePurchaseDate()
	})
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (u *LicenseUpsertOne) ClearPurchaseDate() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearPurchaseDate()
	})
}

// SetPurchaseCost sets the "purchase_cost" field.
func (u *LicenseUpsertOne) SetPurchaseCost(v float64) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetPurchaseCost(v)
	})
}

// AddPurchaseCost adds v to the "purchase_cost" field.
func (u *LicenseUpsertOne) AddPurchaseCost(v float64) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.AddPurchaseCost(v)
	})
}

// UpdatePurchaseCost sets the "purchase_cost" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdatePurchaseCost() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdatePurchaseCost()
	})
}

// ClearPurchaseCost clears the value of the "purchase_cost" field.
func (u *LicenseUpsertOne) ClearPurchaseCost() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearPurchaseCost()
	})
}

// SetOrderNumber sets the "order_number" field.
func (u *LicenseUpsertOne) SetOrderNumber(v string) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetOrderNumber(v)
	})
}

// UpdateOrderNumber sets the "order_number" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateOrderNumber() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateOrderNumber()
	})
}

// ClearOrderNumber clears the value of the "order_number" field.
func (u *LicenseUpsertOne) ClearOrderNumber() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearOrderNumber()
	})
}

// SetValidFrom sets the "valid_from" field.
func (u *LicenseUpsertOne) SetValidFrom(v time.Time) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetValidFrom(v)
	})
}

// UpdateValidFrom sets the "valid_from" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateValidFrom() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateValidFrom()
	})
}

// ClearValidFrom clears the value of the "valid_from" field.
func (u *LicenseUpsertOne) ClearValidFrom() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearValidFrom()
	})
}

// SetValidTo sets the "valid_to" field.
func (u *LicenseUpsertOne) SetValidTo(v time.Time) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetValidTo(v)
	})
}

// UpdateValidTo sets the "valid_to" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateValidTo() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateValidTo()
	})
}

// ClearValidTo clears the value of the "valid_to" field.
func (u *LicenseUpsertOne) ClearValidTo() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearValidTo()
	})
}

// SetNotes sets the "notes" field.
func (u *LicenseUpsertOne) SetNotes(v string) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateNotes() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *LicenseUpsertOne) ClearNotes() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearNotes()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LicenseUpsertOne) SetMetadata(v map[string]interface{}) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateMetadata() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LicenseUpsertOne) ClearMetadata() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearMetadata()
	})
}

// SetStatus sets the "status" field.
func (u *LicenseUpsertOne) SetStatus(v string) *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LicenseUpsertOne) UpdateStatus() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *LicenseUpsertOne) ClearStatus() *LicenseUpsertOne {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *LicenseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LicenseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LicenseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LicenseUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LicenseUpsertOne.ID is not supported by MySQL driver. Use LicenseUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LicenseUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LicenseCreateBulk is the builder for creating many License entities in bulk.
type LicenseCreateBulk struct {
	config
	err      error
	builders []*LicenseCreate
	conflict []sql.ConflictOption
}

// Save creates the License entities in the database.
func (_c *LicenseCreateBulk) Save(ctx context.Context) ([]*License, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*License, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LicenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LicenseCreateBulk) SaveX(ctx context.Context) []*License {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LicenseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LicenseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.License.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LicenseUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *LicenseCreateBulk) OnConflict(opts ...sql.ConflictOption) *LicenseUpsertBulk {
	_c.conflict = opts
	return &LicenseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.License.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LicenseCreateBulk) OnConflictColumns(columns ...string) *LicenseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LicenseUpsertBulk{
		create: _c,
	}
}

// LicenseUpsertBulk is the builder for "upsert"-ing
// a bulk of License nodes.
type LicenseUpsertBulk struct {
	create *LicenseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.License.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(license.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LicenseUpsertBulk) UpdateNewValues() *LicenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(license.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(license.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(license.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.License.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LicenseUpsertBulk) Ignore() *LicenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LicenseUpsertBulk) DoNothing() *LicenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LicenseCreateBulk.OnConflict
// documentation for more info.
func (u *LicenseUpsertBulk) Update(set func(*LicenseUpsert)) *LicenseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LicenseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *LicenseUpsertBulk) SetCreateBy(v uint32) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *LicenseUpsertBulk) AddCreateBy(v uint32) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateCreateBy() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *LicenseUpsertBulk) ClearCreateBy() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *LicenseUpsertBulk) SetUpdateBy(v uint32) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *LicenseUpsertBulk) AddUpdateBy(v uint32) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateUpdateBy() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *LicenseUpsertBulk) ClearUpdateBy() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *LicenseUpsertBulk) SetUpdateTime(v time.Time) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateUpdateTime() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *LicenseUpsertBulk) ClearUpdateTime() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *LicenseUpsertBulk) SetDeleteTime(v time.Time) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateDeleteTime() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *LicenseUpsertBulk) ClearDeleteTime() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *LicenseUpsertBulk) SetName(v string) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateName() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateName()
	})
}

// SetSupplierID sets the "supplier_id" field.
func (u *LicenseUpsertBulk) SetSupplierID(v string) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetSupplierID(v)
	})
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateSupplierID() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateSupplierID()
	})
}

// ClearSupplierID clears the value of the "supplier_id" field.
func (u *LicenseUpsertBulk) ClearSupplierID() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearSupplierID()
	})
}

// SetPurchaseDate sets the "purchase_date" field.
func (u *LicenseUpsertBulk) SetPurchaseDate(v time.Time) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetPurchaseDate(v)
	})
}

// UpdatePurchaseDate sets the "purchase_date" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdatePurchaseDate() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdatePurchaseDate()
	})
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (u *LicenseUpsertBulk) ClearPurchaseDate() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearPurchaseDate()
	})
}

// SetPurchaseCost sets the "purchase_cost" field.
func (u *LicenseUpsertBulk) SetPurchaseCost(v float64) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetPurchaseCost(v)
	})
}

// AddPurchaseCost adds v to the "purchase_cost" field.
func (u *LicenseUpsertBulk) AddPurchaseCost(v float64) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.AddPurchaseCost(v)
	})
}

// UpdatePurchaseCost sets the "purchase_cost" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdatePurchaseCost() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdatePurchaseCost()
	})
}

// ClearPurchaseCost clears the value of the "purchase_cost" field.
func (u *LicenseUpsertBulk) ClearPurchaseCost() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearPurchaseCost()
	})
}

// SetOrderNumber sets the "order_number" field.
func (u *LicenseUpsertBulk) SetOrderNumber(v string) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetOrderNumber(v)
	})
}

// UpdateOrderNumber sets the "order_number" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateOrderNumber() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateOrderNumber()
	})
}

// ClearOrderNumber clears the value of the "order_number" field.
func (u *LicenseUpsertBulk) ClearOrderNumber() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearOrderNumber()
	})
}

// SetValidFrom sets the "valid_from" field.
func (u *LicenseUpsertBulk) SetValidFrom(v time.Time) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetValidFrom(v)
	})
}

// UpdateValidFrom sets the "valid_from" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateValidFrom() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateValidFrom()
	})
}

// ClearValidFrom clears the value of the "valid_from" field.
func (u *LicenseUpsertBulk) ClearValidFrom() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearValidFrom()
	})
}

// SetValidTo sets the "valid_to" field.
func (u *LicenseUpsertBulk) SetValidTo(v time.Time) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetValidTo(v)
	})
}

// UpdateValidTo sets the "valid_to" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateValidTo() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateValidTo()
	})
}

// ClearValidTo clears the value of the "valid_to" field.
func (u *LicenseUpsertBulk) ClearValidTo() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearValidTo()
	})
}

// SetNotes sets the "notes" field.
func (u *LicenseUpsertBulk) SetNotes(v string) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateNotes() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *LicenseUpsertBulk) ClearNotes() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearNotes()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LicenseUpsertBulk) SetMetadata(v map[string]interface{}) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateMetadata() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LicenseUpsertBulk) ClearMetadata() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearMetadata()
	})
}

// SetStatus sets the "status" field.
func (u *LicenseUpsertBulk) SetStatus(v string) *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LicenseUpsertBulk) UpdateStatus() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *LicenseUpsertBulk) ClearStatus() *LicenseUpsertBulk {
	return u.Update(func(s *LicenseUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *LicenseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LicenseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LicenseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LicenseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
